FROM nginx

MAINTAINER "Brijesh K Dhaker <brijeshdhaker@gmail.com>"

COPY docker-hadoop-2.7.4/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY docker-hadoop-2.7.4/nginx/materialize.min.css /data/bde-css/materialize.min.css
COPY docker-hadoop-2.7.4/nginx/bde-hadoop.css /data/bde-css/bde-hadoop.css
