#
#
#
version: '3.1'
#
services:
  #
  # Hadoop namenode
  #
  namenode:
    image: dhc/hadoop:3.2.1
    build:
      context: .
      dockerfile: docker/hadoop/Dockerfile
    hostname: namenode
    container_name: namenode
    ports:
      - "9000:9000"   # HDFS Port
      - "9870:9870"   # HTTP Server
    command: /start-namenode.sh
    env_file:
      - docker/.env
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  #
  #
  datanode:
    image: dhc/hadoop:3.2.1
    command: hdfs datanode
    hostname: datanode
    container_name: datanode
    ports:
      - "9864:9864"  # HTTP Server
      - "9866:9866"  # Streaming Server
      - "9867:9867"  # IPC Server
    env_file:
      - docker/.env
    links:
      - namenode
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Hadoop SecondaryNamenode
  #
  secondarynamenode:
      image: dhc/hadoop:3.2.1
      container_name: secondarynamenode
      hostname: secondarynamenode
      command: hdfs secondarynamenode
      ports:
        - "9868:9868"   # Web-server SecondaryNamenode
      env_file:
        - docker/.env
      links:
        - namenode
      volumes:
        - /apps/hostpath:/apps/hostpath

  #
  # Hadoop ResourceManager
  #
  yarn:
    image: dhc/hadoop:3.2.1
    container_name: yarn
    hostname: yarn
    command: /start-yarn-historyserver.sh
    depends_on:
      - namenode
      - datanode
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"       # Http Port for yarn cluster
      - "19888:19888"     # History WebServer
      - "10020:10020"     # History Server Address
    env_file:
      - docker/.env
    links:
      - namenode
      - datanode
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Hadoop NodeManager
  #
  nodemanager:
      image: dhc/hadoop:3.2.1
      container_name: nodemanager
      hostname: nodemanager
      command: yarn nodemanager
      ports:
        - "8040:8040"    # Localizer NodeManager
        - "8042:8042"    # Http Port NMWebApp
      env_file:
        - docker/.env
      depends_on:
        - namenode
        - datanode
        - yarn
      links:
        - namenode
        - datanode
        - yarn
      volumes:
        - /apps/hostpath:/apps/hostpath
  #
  # postgres sql
  #
  postgres:
    image: dhc/postgres:latest
    container_name: postgres
    hostname: postgres
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    command: /init-setup.sh
    env_file:
      - docker/.env
    ports:
      - "5432:5432"
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Hive
  #
  hive:
    image: dhc/hive:3.2.1
    container_name: hive
    hostname: hive
    build:
      context: .
      dockerfile: docker/hive/Dockerfile
    env_file:
      - docker/.env
    depends_on:
      - namenode
      - datanode
      - postgres
    ports:
      - "10000:10000"
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: dhc/zeppelin:0.9.0
    container_name: zeppelin
    build:
      context: .
      dockerfile: docker/zeppelin/Dockerfile
    env_file:
      - docker/.env
    ports:
      - "9090:8080"
      - "4040:4040"
    volumes:
      - /apps/spark-3.1.2:/opt/spark
      - /apps/hadoop-3.2.1:/opt/hadoop

  #
  #
  #