# docker-compose build
# docker-compose up -d
# docker-compose scale nodemanager=X; # X=integer number --> allows to add more nodes to the hadoop cluster for testing

version: '3.1'
services:

  #
  # Hadoop namenode
  #
  namenode:
    image: dhc/hadoop:3.2.1
    build:
      context: .
      dockerfile: docker/hadoop/Dockerfile
    hostname: namenode
    container_name: namenode
    ports:
      - "9000:9000"   # HDFS Port
      - "9870:9870"   # HTTP Server
    command: /start-namenode.sh
    env_file:
      - docker/.env
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  #
  #
  datanode:
    image: dhc/hadoop:3.2.1
    command: hdfs datanode
    hostname: datanode
    container_name: datanode
    ports:
      - "9864:9864"  # HTTP Server
      - "9866:9866"  # Streaming Server
      - "9867:9867"  # IPC Server
    env_file:
      - docker/.env
    links:
      - namenode
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Hadoop SecondaryNamenode
  #
  secondarynamenode:
      image: dhc/hadoop:3.2.1
      container_name: secondarynamenode
      hostname: secondarynamenode
      command: hdfs secondarynamenode
      ports:
        - "9868:9868"   # Web-server SecondaryNamenode
      env_file:
        - docker/.env
      links:
        - namenode
      volumes:
        - /apps/hostpath:/apps/hostpath

  #
  # Hadoop ResourceManager
  #
  yarn:
    image: dhc/hadoop:3.2.1
    container_name: yarn
    hostname: yarn
    command: /start-yarn-historyserver.sh
    depends_on:
      - namenode
      - datanode
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"       # Http Port for yarn cluster
      - "19888:19888"     # History WebServer
      - "10020:10020"     # History Server Address
    env_file:
      - docker/.env
    links:
      - namenode
      - datanode
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Hadoop NodeManager
  #
  nodemanager:
      image: dhc/hadoop:3.2.1
      container_name: nodemanager
      hostname: nodemanager
      command: yarn nodemanager
      ports:
        - "8040:8040"    # Localizer NodeManager
        - "8042:8042"    # Http Port NMWebApp
      env_file:
        - docker/.env
      depends_on:
        - namenode
        - datanode
        - yarn
      links:
        - namenode
        - datanode
        - yarn
      volumes:
        - /apps/hostpath:/apps/hostpath

  #
  #
  #
#  edgenode:
#    image: dhc/hadoop:3.2.1
#    container_name: edgenode
#    hostname: edgenode
#    links:
#      - yarn
#      - namenode
#    env_file:
#      - docker/.env
#    volumes:
#      - /apps/hadoop-3.2.1:/opt/hadoop
#      - /apps/jdk1.8.0_251:/opt/java
#      - /apps/hostpath:/apps/hostpath

  #
  #
  #