#
#
#
version: "3.5"

services:
  #
  # HDFS & YARN Sandbox
  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.2.1
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - /apps/hostpath/sandbox3/hadoop/dfs/name:/hadoop/dfs/name
      - /apps/hostpath:/apps/hostpath
    environment:
      - CLUSTER_NAME=test
    env_file:
      - sandbox3.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.2.1
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - /apps/hostpath/sandbox3/hadoop/dfs/data:/hadoop/dfs/data
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - sandbox3.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.2.1
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - sandbox3.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.2.1
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - sandbox3.env

  #
  timelineserver:
    image: brijeshdhaker/hadoop-timelineserver:3.2.1
    container_name: timelineserver
    hostname: timelineserver
    restart: always
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - /apps/hostpath/sandbox3/hadoop/yarn/timeline:/tmp/yarn/timeline
      - /apps/hostpath:/apps/hostpath
    env_file:
      - sandbox3.env

  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.2.1
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - /apps/hostpath/sandbox3/hadoop/yarn/history:/tmp/yarn/history
      - /apps/hostpath:/apps/hostpath
    env_file:
      - sandbox3.env

  #
  # Hive Server
  #
  hive-postgresql:
    image: brijeshdhaker/hive-postgresql:3.1.2
    hostname: hive-postgresql
    container_name: hive-postgresql
    ports:
      - "5432:5432"
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  hive-metastore:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - sandbox3.env
    command: /opt/hive-3.1.2/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-postgresql:5432"
    links:
      - hive-postgresql
    ports:
      - "9083:9083"
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  hive-server:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-server
    container_name: hive-server
    env_file:
      - sandbox3.env
    links:
      - hive-metastore
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-postgresql/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - /apps/hostpath:/apps/hostpath

  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: apache/zeppelin:0.10.0
    container_name: zeppelin
    hostname: zeppelin
    env_file:
      - sandbox3.env
    ports:
      - "9080:8080"
      - "4040:4040"
    volumes:
      - /apps/hostpath:/apps/hostpath
      - /opt/sandbox/hadoop-3.2.1:/opt/hadoop-3.2.1
      - /opt/sandbox/hbase-2.4.9:/opt/hbase-2.4.9
      - /opt/sandbox/hbase-1.1.7:/opt/hbase-client
      - /opt/sandbox/hive-3.1.2:/opt/hive-3.1.2
      - /opt/sandbox/spark-3.1.2:/opt/spark-3.1.2
      - /apps/hostpath/sandbox3/zeppelin/conf:/opt/zeppelin/conf
      - /apps/hostpath/.m2:/opt/zeppelin/.m2
      - /apps/hostpath/.ivy2:/opt/zeppelin/.ivy2

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net

