flink:
  hadoop:
    fs:
      default-scheme: s3a://defaultfs
      s3a:
        secret:
          key: zjd8T0hXFGtfemVQ6AH3yBAPASJNXNbVSx5iddqG
        impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        access:
          key: pgm2H2bR7a5kMc5XCYdO
        aws:
          credentials:
            provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
        endpoint: http://minio.sandbox.net:9010
        path:
          style:
            access: true
blob:
  server:
    port: '6124'
rest:
  flamegraph:
    enabled: 'true'
  bind-port: '8081'
  bind-address: 0.0.0.0
  address: flink-jobmanager
  profiling:
    enabled: true
fs:
  default-scheme: s3a://defaultfs/
jobmanager:
  execution:
    failover-strategy: region
  rpc:
    address: flink-jobmanager
    port: 6123
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
state:
  savepoints:
    dir: s3a://defaultfs/state/savepoints
  backend:
    type: hashmap
  checkpoints:
    dir: s3a://defaultfs/state/checkpoints
query:
  server:
    port: '6125'
s3:
  secret-key: password
  endpoint: http://minio.sandbox.net:9010
  access-key: admin
  path:
    style:
      access: true
io:
  tmp:
    dirs: /tmp
execution:
  checkpointing:
    savepoint-dir: s3a://defaultfs/execution/savepoints
    dir: s3a://defaultfs/execution/
    interval: 10s
taskmanager:
  host: flink-taskmanager
  numberOfTaskSlots: '4'
  memory:
    process:
      size: 1728m
  bind-host: 0.0.0.0
parallelism:
  default: 4
env:
  java:
    opts:
      all: --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
  log:
    max: 5
    dir: /apps/var/logs/flink
    level: INFO
web:
  cancel:
    enable: true
  submit:
    enable: true
