#
# docker compose -f bd-flink-spend-report/docker-compose.yaml up -d
# docker compose -f bd-flink-spend-report/docker-compose.yaml down
#

# docker compose -f bd-flink-spend-report/docker-compose.yaml up -d flink-jobmanager
# docker compose -f bd-flink-spend-report/docker-compose.yaml kill flink-jobmanager

# docker compose -f bd-flink-spend-report/docker-compose.yaml up -d flink-taskmanager
# docker compose -f bd-flink-spend-report/docker-compose.yaml kill flink-taskmanager

#
# docker compose -f bd-flink-spend-report/docker-compose.yaml up -d mysqlserver
# docker compose -f bd-flink-spend-report/docker-compose.yaml kill mysqlserver
# docker compose -f bd-flink-spend-report/docker-compose.yaml exec mysqlserver mysql -DSANDBOXDB -uflink -pp@SSW0rd
# docker compose -f bd-flink-spend-report/docker-compose.yaml exec mysqlserver mysql -DSANDBOXDB -uflink -pp@SSW0rd -e "select * from spend_report;"
# docker compose -f bd-flink-spend-report/docker-compose.yaml exec mysqlserver mysql -DSANDBOXDB -uflink -pp@SSW0rd -e "select count(*) from spend_report;"
#


# docker compose -f bd-flink-spend-report/docker-compose.yaml exec kafkabroker kafka-console-consumer --bootstrap-server kafkabroker.sandbox.net:9092 --topic transactions
#


include:
  - path: ../bd-docker-sandbox/dc-mysqlserver.yaml
  - path: ../bd-docker-sandbox/dc-kafka-cluster.yaml
  - path: ../bd-docker-sandbox/dc-flink-cluster.yaml

services:

  ##
  data-generator:
      image: flink/bd-data-generator:1.17.2
      build: ../bd-data-generator
      container_name: data-generator
      depends_on:
        kafkabroker:
          condition: service_healthy

  ##
  flink-spend-client:
    build: .
    image: flink/flink-spend-report:1.17.2
    container_name: flink-spend-client
    command: "flink run -d /opt/flink/usrlib/flink-spend-report.jar --bootstrap.servers kafkabroker.sandbox.net:9092 --checkpointing --event-time"
    depends_on:
      flink-jobmanager:
        condition: service_healthy
      kafkabroker:
        condition: service_healthy
    volumes:
      - ../bd-docker-sandbox/conf:/opt/flink/conf
      - sandbox_flink_data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  ##
  grafana:
    image: grafana/grafana:7.5.8
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      mysqlserver:
        condition: service_healthy
      kafkabroker:
        condition: service_healthy
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboard.json:/etc/grafana/dashboard.json
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini


#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net