#
#

version: '3.5'

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - '2181'
    volumes:
      - /apps/clusters/zookeeper/data_1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  #
  zookeeper2:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - '2181'
    volumes:
      - /apps/clusters/zookeeper/data_2:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

  #
  zookeeper3:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - '2181'
    volumes:
      - /apps/clusters/zookeeper/data_3:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

  #
  kafka1:
    image: 'bitnami/kafka:latest'
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092'
      - '19092:19092'
    volumes:
      - /apps/clusters/kafka/data_1:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://localhost:19092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
  #
  kafka2:
    image: 'bitnami/kafka:latest'
    hostname: kafka2
    container_name: kafka2
    ports:
      - '9092'
      - '29092:29092'
    volumes:
      - /apps/clusters/kafka/data_2:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m

  #
  kafka3:
    image: 'bitnami/kafka:latest'
    hostname: kafka3
    container_name: kafka3
    ports:
      - '9092'
      - '39092:39092'
    volumes:
      - /apps/clusters/kafka/data_3:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://localhost:39092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m

#
volumes:
  zookeeper1_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net