version: '2'

services:
  #
  kafka1:
    image: 'bitnami/kafka:latest'
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092'
    volumes:
      - /apps/hostpath/kafka/cluster/data_1:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  #
  kafka2:
    image: 'bitnami/kafka:latest'
    hostname: kafka2
    container_name: kafka2
    ports:
      - '9092'
    volumes:
      - /apps/hostpath/kafka/cluster/data_2:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  #
  kafka3:
    image: 'bitnami/kafka:latest'
    hostname: kafka3
    container_name: kafka3
    ports:
      - '9092'
    volumes:
      - /apps/hostpath/kafka/cluster/data_3:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
