version: "3.5"
#
services:
#
  hbase:
    image: brijeshdhaker/hbase-standalone:2.4.6
    build:
      context: .
      dockerfile: docker-hbase/standalone/Dockerfile
    container_name: hbase
    hostname: hbase
    volumes:
      - "/apps/hostpath:/apps/hostpath"
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - docker-hbase/hbase-standalone.env

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net