#
# docker volume create --name sandbox_hive_data --opt type=none --opt device=/apps/sandbox/hive --opt o=bind
# docker volume create --name sandbox_hive_312 --opt type=none --opt device=/opt/hive-3.1.2 --opt o=bind
# docker volume create --name sandbox_tez_092 --opt type=none --opt device=/opt/tez-0.9.2 --opt o=bind
#
---
version: "3.5"
#
services:

  #
  # Hive Server
  #
  metastore:
    image: brijeshdhaker/hive:3.1.2
    container_name: metastore
    hostname: metastore.sandbox.net
    env_file:
      - envs/docker_hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "mysqlserver:3306"
    ports:
      - "9083:9083"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_321:/opt/hadoop
      - sandbox_tez_092:/opt/tez
      - ./conf/kerberos:/etc/kerberos

  #
  hiveserver:
    image: brijeshdhaker/hive:3.1.2
    container_name: hiveserver
    hostname: hiveserver.sandbox.net
    env_file:
      - envs/docker_hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://mysqlserver:3306/metastore?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_321:/opt/hadoop
      - sandbox_tez_092:/opt/tez
      - ./conf/kerberos:/etc/kerberos

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_hadoop_321:
    external: true
  sandbox_tez_092:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net