version: "3.5"

services:

  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.0.0
    build:
      context: .
      dockerfile: docker-hadoop-3.0.0/namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker-hadoop-3.0.0/hadoop-3.0.0.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.0.0
    build:
      context: .
      dockerfile: docker-hadoop-3.0.0/datanode/Dockerfile
    container_name: datanode
    hostname: datanode
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - docker-hadoop-3.0.0/hadoop-3.0.0.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.0.0
    build:
      context: .
      dockerfile: docker-hadoop-3.0.0/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8088:8088"
      - "8025:8025"
      - "8032:8032"
      - "8050:8050"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:9870  datanode:9864"
    env_file:
      - docker-hadoop-3.0.0/hadoop-3.0.0.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.0.0
    build:
      context: .
      dockerfile: docker-hadoop-3.0.0/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8042:8042"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:9870  datanode:9864 resourcemanager:8088"
    env_file:
      - docker-hadoop-3.0.0/hadoop-3.0.0.env

  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.0.0
    build:
      context: .
      dockerfile: docker-hadoop-3.0.0/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:9870  datanode:9864 resourcemanager:8088"
    volumes:
      - /apps/hostpath:/apps/hostpath
    env_file:
      - docker-hadoop-3.0.0/hadoop-3.0.0.env

#
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net