version: "3.5"
#
services:
#
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_DATA_DIR: /apps/hostpath/hbase/1.1.1/zookeeper-distributed
      ZOO_DATA_LOG_DIR: /apps/hostpath/hbase/1.1.1/zookeeper-log
    ports:
      - 2181:2181
    volumes:
      - "/apps/hostpath:/apps/hostpath"


#
  hbase-master:
    image: brijeshdhaker/hbase-master:1.1.1
    build:
      context: .
      dockerfile: docker-hbase-1.1.1/hmaster/Dockerfile
    hostname: hbase-master
    container_name: hbase-master
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    env_file:
      - docker-hbase-1.1.1/hbase-distributed.env
    ports:
      - 16010:16010
    volumes:
      - "/apps/hostpath:/apps/hostpath"

#
  hbase-region:
    image: brijeshdhaker/hbase-regionserver:1.1.1
    build:
      context: .
      dockerfile: docker-hbase-1.1.1/hregionserver/Dockerfile
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - docker-hbase-1.1.1/hbase-distributed.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    ports:
      - 16030:16030
    volumes:
      - "/apps/hostpath:/apps/hostpath"

#
networks:
  default:
     name: bigdata.net