#
#
# docker volume create --name sandbox_hbase_300 --opt type=none --opt device=/opt/hbase-3.0.0 --opt o=bind
# docker volume create --name sandbox_hbase_117 --opt type=none --opt device=/opt/hbase-1.1.7 --opt o=bind
#

#
#
#
---
version: "3.9"

services:
  #
  # Zookeeper Server
  # zookeeper:3.5.7
  zookeeper:
    image: zookeeper:3.5.7
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "8080:8080"
    volumes:
      - sandbox_apps_path:/apps
      - /apps/sandbox/zookeeper:/zookeeper
      - ./conf/zookeeper:/conf
      - ./conf/kerberos:/etc/kerberos
    environment:
      JVMFLAGS: "-Djava.security.auth.login.config=/conf/jaas.conf -Djava.security.krb5.conf=/etc/kerberos/krb5.conf"
      KRB5_CONFIG: "/etc/kerberos/krb5.conf"

  #
  # Hbase Server
  #
  hmaster:
    image: brijeshdhaker/hbase-master:3.0.0
    hostname: hmaster.sandbox.net
    container_name: hmaster
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181"
    env_file:
      - envs/docker_hbase.env
    ports:
      - "16000:16000"
      - "16010:16010"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_321:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hbase/hbase-env.sh:/opt/hbase/conf/hbase-env.sh
      - ./conf/hbase/hmaster-jaas.conf:/opt/hbase/conf/zk-jaas.conf

  #
  hregion:
    image: brijeshdhaker/hbase-regionserver:3.0.0
    hostname: hregion.sandbox.net
    container_name: hregion
    env_file:
      - envs/docker_hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181 hmaster.sandbox.net:16010"
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_321:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hbase/hbase-env.sh:/opt/hbase/conf/hbase-env.sh
      - ./conf/hbase/hregion-jaas.conf:/opt/hbase/conf/zk-jaas.conf
      - ./conf/hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml

#
volumes:
#
  sandbox_apps_path:
    external: true
  sandbox_logs:
    external: true
#
  sandbox_zookeeper_secrets:
    external: true
  sandbox_zookeeper_data:
    external: true
  sandbox_zookeeper_log:
    external: true
#
  sandbox_hadoop_321:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
