#
#
#
---
#

version: '3.5'
services:
  #
  # Apache NiFi
  #
  hdf-nifi:
    image: hortonworks/nifi:latest
    container_name: hdf-nifi
    hostname: hdf-nifi
    restart: always
    ports:
      - "19090:8080"
      - "19443:8443"
    volumes:
      - /apps/hostpath:/apps/hostpath

#
networks:
  default:
    name: bigdata.net