#
# docker volume create --name sandbox_host_path --opt type=none --opt device=/apps/hostpath --opt o=bind
# docker volume create --name sandbox_base_path --opt type=none --opt device=/apps/sandbox --opt o=bind
#
# docker volume create --name sandbox_hadoop_334_dfs --opt type=none --opt device=/apps/sandbox/hadoop-3.3.5/dfs --opt o=bind
# docker volume create --name sandbox_hadoop_334_yarn --opt type=none --opt device=/apps/sandbox/hadoop-3.3.5/yarn --opt o=bind
# docker volume create --name sandbox_hadoop_334_mapred --opt type=none --opt device=/apps/sandbox/hadoop-3.3.5/mapred --opt o=bind
#
# docker volume create --name sandbox_spark_312 --opt type=none --opt device=/opt/spark-3.1.2 --opt o=bind
# docker volume create --name sandbox_hadoop_274 --opt type=none --opt device=/opt/hadoop-2.7.4 --opt o=bind
#
# docker volume create --name sandbox_hadoop_334 --opt type=none --opt device=/opt/hadoop-3.3.4 --opt o=bind
# docker volume create --name sandbox_spark_340 --opt type=none --opt device=/opt/spark-3.4.0 --opt o=bind
# docker volume create --name sandbox_hive_312 --opt type=none --opt device=/opt/hive-3.1.2 --opt o=bind
# docker volume create --name sandbox_hbase_249 --opt type=none --opt device=/opt/hbase-2.4.9 --opt o=bind
# docker volume create --name sandbox_hbase_117 --opt type=none --opt device=/opt/hbase-1.1.7 --opt o=bind
#

version: "3.9"

services:
  #
  kdcserver:
    image: brijeshdhaker/kdcserver:22.04
    container_name: kdcserver
    hostname: kdcserver.sandbox.net
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - /dev/urandom:/dev/random      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - sandbox_krb5_stash:/etc/krb5kdc
      - sandbox_krb5_principal:/var/lib/krb5kdc/
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    env_file:
      - ./envs/docker_kerberos.env
    ports:
      - "749:749"
      - "88:88/udp"

  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/namenode/Dockerfile
    container_name: namenode
    hostname: namenode.sandbox.net
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hadoop/conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
      - ./conf/hadoop/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      CLUSTER_NAME: "docker-sandbox"
    env_file:
      - envs/docker_hadoop334.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/datanode/Dockerfile
    container_name: datanode
    hostname: datanode.sandbox.net
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: no
#    command: ["/usr/sbin/sshd", "-D"]
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hadoop/conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
#      - ./conf/hadoop/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./conf/hadoop/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000"
    env_file:
      - envs/docker_hadoop334.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager.sandbox.net
    restart: always
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
      - ./conf/yarn/fair-scheduler.xml:/opt/hadoop-3.3.4/etc/hadoop/fair-scheduler.xml
      - ./conf/yarn/capacity-scheduler.xml:/opt/hadoop-3.3.4/etc/hadoop/capacity-scheduler.xml
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    env_file:
      - envs/docker_hadoop334.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager.sandbox.net
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088"
    env_file:
      - envs/docker_hadoop334.env


  #
  # YARN MR History Server
  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver.sandbox.net
    restart: always
    ports:
      - "19888:19888"
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_mr:/mapred
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - envs/docker_hadoop334.env

  #
  # YARN Timeline Server
  #
  timelineserver:
    image: brijeshdhaker/hadoop-timelineserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/timelineserver/Dockerfile
    container_name: timelineserver
    hostname: timelineserver.sandbox.net
    restart: no
    ports:
      - "8188:8188"
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - envs/docker_hadoop334.env

  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/ubuntu:22.04
    container_name: gateway
    hostname: gateway.sandbox.net
    restart: always
    command:
      - "/usr/sbin/sshd"
      - "-D"
    ports:
      - "2222:22"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_hbase_249:/opt/hbase
      - sandbox_hbase_117:/opt/hbase-client
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_340:/opt/spark
      - sandbox_maven_363:/opt/maven-3.6.3
      - ./conf/kerberos:/etc/kerberos
      - ./conf/gateway/sandbox.profile:/home/brijeshdhaker/sandbox.profile
      - ./conf/gateway/settings.xml:/home/brijeshdhaker/.m2/settings.xml
    environment:
      CLUSTER_NAME: "docker-sandbox"
    env_file:
      - ./envs/docker_gateway.env



#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_hadoop_334_dfs:
    external: true
  sandbox_hadoop_334_mr:
    external: true
  sandbox_hadoop_334_yarn:
    external: true
  sandbox_hadoop_334:
    external: true
  sandbox_hive_312:
    external: true
  sandbox_spark_340:
    external: true
  sandbox_hbase_249:
    external: true
  sandbox_hbase_117:
    external: true
  sandbox_maven_363:
    external: true
  sandbox_krb5_stash:
    external: true
  sandbox_krb5_principal:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net