#
# docker volume create --name sandbox_hive_data --opt type=none --opt device=/apps/sandbox/hive --opt o=bind
# docker volume create --name sandbox_hive_312 --opt type=none --opt device=/opt/hive-3.1.2 --opt o=bind
# docker volume create --name sandbox_tez_010 --opt type=none --opt device=/opt/tez-0.10.2 --opt o=bind
#
---
version: "3.5"
#
services:

  #
  # Hive Server
  #
  hive-metastore:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - envs/docker_hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "mysqlserver:3306"
    ports:
      - "9083:9083"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_tez_010:/opt/tez

  #
  hive-server:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-server
    container_name: hive-server
    env_file:
      - envs/docker_hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://mysqlserver:3306/metastore?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false"
#      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore:9083"
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_tez_010:/opt/tez

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_hadoop_334:
    external: true
  sandbox_tez_010:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net