version: "3.5"

services:
  #
  hadoop-base:
    image: big-data/hadoop-base:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/base/Dockerfile

  #
  namenode:
    image: big-data/hadoop-namenode:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker-hadoop/hadoop.env

  #
  datanode:
    image: big-data/hadoop-datanode:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/datanode/Dockerfile
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - docker-hadoop/hadoop.env

  #
  resourcemanager:
    image: big-data/hadoop-resourcemanager:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - docker-hadoop/hadoop.env

  #
  nodemanager1:
    image: big-data/hadoop-nodemanager:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - docker-hadoop/hadoop.env

  #
  hadoop-historyserver:
    image: big-data/hadoop-historyserver:3.2.1
    build:
      context: .
      dockerfile: docker-hadoop/historyserver/Dockerfile
    container_name: hadoop-historyserver
    hostname: hadoop-historyserver
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - /apps/hostpath:/apps/hostpath
    env_file:
      - docker-hadoop/hadoop.env

#
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
#
networks:
  default:
    name: hadoop.net