#
#
#
---
#

version: "3.5"
#
services:
#
  hbase-master:
    image: brijeshdhaker/hbase-master:2.4.9
    build:
      context: .
      dockerfile: docker-hbase-2.4.9/hmaster/Dockerfile
    hostname: hbase-master
    container_name: hbase-master
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    env_file:
      - docker-hbase-2.4.9/hbase-distributed.env
    ports:
      - 16010:16010
    volumes:
      - "/apps/hostpath:/apps/hostpath"

#
  hbase-region:
    image: brijeshdhaker/hbase-regionserver:2.4.9
    build:
      context: .
      dockerfile: docker-hbase-2.4.9/hregionserver/Dockerfile
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - docker-hbase-2.4.9/hbase-distributed.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    ports:
      - 16030:16030
    volumes:
      - "/apps/hostpath:/apps/hostpath"

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net