version: "3.5"
#
services:
#
  hive-postgresql:
    image: brijeshdhaker/hive-postgresql:3.1.2
    build:
      context: .
      dockerfile: docker-hive-3.1.2/postgres/Dockerfile
    hostname: hive-postgresql
    container_name: hive-postgresql
    ports:
      - "5432:5432"
    volumes:
      - /apps/hostpath:/apps/hostpath

#
#  presto-coordinator:
#    image: shawnzhu/prestodb:0.181
#    hostname: presto-coordinator
#    container_name: presto-coordinator
#    ports:
#      - "8080:8080"

#
  hive-metastore:
    image: brijeshdhaker/hive:3.1.2
    build:
      context: .
      dockerfile: docker-hive-3.1.2/hive/Dockerfile
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - docker-hive-3.1.2/hive-3.1.2.env
    command: /opt/hive-3.1.2/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-postgresql:5432"
    links:
      - hive-postgresql
    ports:
      - "9083:9083"
    volumes:
      - /apps/hostpath:/apps/hostpath

#
  hive-server:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-server
    container_name: hive-server
    env_file:
      - docker-hive-3.1.2/hive-3.1.2.env
    links:
      - hive-metastore  
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-postgresql/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - /apps/hostpath:/apps/hostpath
      - /opt/hbase-2.4.6:/opt/hbase-2.4.6

#
volumes:
  namenode:
  datanode:

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net