#
# docker volume create --name sandbox_host_path --opt type=none --opt device=/apps/hostpath --opt o=bind
# docker volume create --name sandbox_base_path --opt type=none --opt device=/apps/sandbox --opt o=bind
#
# docker volume create --name sandbox_hadoop_334_dfs --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/dfs --opt o=bind
# docker volume create --name sandbox_hadoop_334_yarn --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/yarn --opt o=bind
# docker volume create --name sandbox_hadoop_334_mr --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/mr --opt o=bind
#
# docker volume create --name sandbox_spark_312 --opt type=none --opt device=/opt/spark-3.1.2 --opt o=bind
# docker volume create --name sandbox_hadoop_274 --opt type=none --opt device=/opt/hadoop-2.7.4 --opt o=bind
#
# docker volume create --name sandbox_hadoop_334 --opt type=none --opt device=/opt/hadoop-3.3.4 --opt o=bind
# docker volume create --name sandbox_spark_340 --opt type=none --opt device=/opt/spark-3.4.0 --opt o=bind
# docker volume create --name sandbox_hive_312 --opt type=none --opt device=/opt/hive-3.1.2 --opt o=bind
# docker volume create --name sandbox_hbase_249 --opt type=none --opt device=/opt/hbase-2.4.9 --opt o=bind
# docker volume create --name sandbox_hbase_117 --opt type=none --opt device=/opt/hbase-1.1.7 --opt o=bind
#

version: "3.9"

services:
  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
    environment:
      - CLUSTER_NAME=docker-sandbox
    env_file:
      - envs/docker_hadoop334.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/datanode/Dockerfile
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - envs/docker_hadoop334.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/yarn/fair-scheduler.xml:/opt/hadoop-3.3.4/etc/hadoop/fair-scheduler.xml
      - ./conf/yarn/capacity-scheduler.xml:/opt/hadoop-3.3.4/etc/hadoop/capacity-scheduler.xml
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - envs/docker_hadoop334.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - envs/docker_hadoop334.env


  #
  # YARN MR History Server
  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - "19888:19888"
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_mr:/mr
    env_file:
      - envs/docker_hadoop334.env

  #
  # YARN Timeline Server
  #
  timelineserver:
    image: brijeshdhaker/hadoop-timelineserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/timelineserver/Dockerfile
    container_name: timelineserver
    hostname: timelineserver
    restart: always
    ports:
      - "8188:8188"
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
    env_file:
      - envs/docker_hadoop334.env

  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/edgenode:3.3.4
    hostname: gateway
    container_name: gateway
    restart: always
    ports:
      - "22:22"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_hbase_249:/opt/hbase
      - sandbox_hbase_117:/opt/hbase-client
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_340:/opt/spark
      - sandbox_maven_363:/opt/maven-3.6.3
      - ./conf/gateway/sandbox.profile:/home/brijeshdhaker/sandbox.profile
      - ./conf/gateway/settings.xml:/home/brijeshdhaker/.m2/settings.xml
    environment:
      CLUSTER_NAME: "docker-sandbox"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    env_file:
      - ./envs/docker_gateway.env

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_hadoop_334_dfs:
    external: true
  sandbox_hadoop_334_mr:
    external: true
  sandbox_hadoop_334_yarn:
    external: true
  sandbox_hadoop_334:
    external: true
  sandbox_hive_312:
    external: true
  sandbox_spark_340:
    external: true
  sandbox_hbase_249:
    external: true
  sandbox_hbase_117:
    external: true
  sandbox_maven_363:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net