#
# docker volume create --name sandbox_krb5_stash --opt type=none --opt device=/apps/hostpath/kerberos/ --opt o=bind
# docker volume create --name sandbox_krb5_principal --opt type=none --opt device=/apps/hostpath/kerberos/ --opt o=bind

#
# Based on https://github.com/ist-dsi/docker-kerberos
#

version: "3.9"
services:
  #
  kdcserver:
    image: brijeshdhaker/kdcserver:22.04
    hostname: 'kdcserver'
    container_name: kdcserver
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - /dev/urandom:/dev/random      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - krb5_stash:/etc/krb5kdc
      - krb5_principal:/var/lib/krb5kdc/
    env_file:
      - ./envs/docker_kerberos.env
    ports:
      - "749:749"
      - "88:88/udp"

#
volumes:
  #
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  krb5_stash:
    external: true
  krb5_principal:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net