#
# docker volume create --name krb5_stash --opt type=none --opt device=/apps/hostpath/kerberos/stash --opt o=bind
# docker volume create --name krb5_principal --opt type=none --opt device=/apps/hostpath/kerberos/principals --opt o=bind
#
# Based on https://github.com/ist-dsi/docker-kerberos
version: "3.9"
services:
  #
  kdcserver:
    image: brijeshdhaker/kdcserver:22.04
    hostname: 'kdcserver'
    container_name: kdcserver
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
      - krb5_stash:/etc/krb5kdc
      - krb5_principal:/var/lib/krb5kdc/
    env_file:
      - ./envs/docker_kerberos.env
    ports:
      - "749:749"
      - "88:88/udp"

  #
  kdcclient:
    image: brijeshdhaker/kdcclient:22.04
    hostname: 'kdcclient'
    container_name: kdcclient
    depends_on:
      - kdcserver
    env_file:
      - ./envs/docker_kerberos.env

#
volumes:
  #
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  krb5_stash:
    external: true
  krb5_principal:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net