#
#
#

version: '3.5'
services:
#
  minio:
    image: big-data/minio:latest
    build:
      context: .
      dockerfile: docker-minio/minio/Dockerfile
    env_file:
      - docker-minio/minio.env
    ports:
      - "9000:9000"
      - "40000:40000"
    command: server /apps/hostpath/minio --console-address 0.0.0.0:40000
    volumes:
      - /apps/hostpath:/apps/hostpath

#
  #
  minio-setup:
    image: big-data/mc:latest
    build:
      context: .
      dockerfile: docker-minio/mc/Dockerfile
    depends_on:
      - minio
    container_name: minio-setup
    env_file:
      - docker-minio/minio.env
    entrypoint: /setup.sh

#
networks:
  default:
    name: bigdata.net
