#
# docker volume create --name sandbox_cassandra_data --opt type=none --opt device=/apps/sandbox/cassandra/data --opt o=bind
# docker volume create --name sandbox_cassandra_conf --opt type=none --opt device=/apps/sandbox/cassandra/conf --opt o=bind
#
---
version: "3.9"

services:
  #
  # Cassandra Server
  #
  opensshd:
    image: brijeshdhaker/ubuntu-openssh:22.04
    hostname: opensshd
    container_name: opensshd
    restart: always
    ports:
      - "22:22"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_cassandra_data:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net