#
#
#
---
#

version: '3.5'
services:
  #
  # HDFS & YARN Sandbox
  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.2.1
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox3_hadoop_dfs_name:/hadoop/dfs/name
      - sandbox3_apps_hostpath:/apps/hostpath
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker-zeppelin/zeppelin.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.2.1
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - sandbox3_hadoop_dfs_data:/hadoop/dfs/data
      - sandbox3_apps_hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - docker-zeppelin/zeppelin.env


  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin
    env_file:
      - docker-zeppelin/zeppelin.env
    ports:
      - "9080:8080"
      - "4040:4040"
    volumes:
      - sandbox3_apps_hostpath:/apps/hostpath
      - sandbox3_hadoop:/opt/hadoop-3.2.1
      - sandbox3_hive:/opt/hive-3.1.2
      - sandbox3_spark:/opt/spark-3.1.2

#
volumes:
  sandbox3_apps_hostpath:
    external: true
  sandbox3_hadoop_dfs_name:
    external: true
  sandbox3_hadoop_dfs_data:
    external: true
  sandbox3_hadoop_yarn_history:
    external: true
  sandbox3_hadoop:
    external: true
  sandbox3_hbase:
    external: true
  sandbox3_hbase_client:
    external: true
  sandbox3_hive:
    external: true
  sandbox3_spark:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net