#
#
# docker volume create --name sandbox_host_path --opt type=none --opt device=/apps/hostpath --opt o=bind
# docker volume create --name sandbox_base_path --opt type=none --opt device=/apps/sandbox --opt o=bind
#
# docker volume create --name sandbox_zookeeper_data --opt type=none --opt device=/apps/sandbox/zookeeper/data --opt o=bind
# docker volume create --name sandbox_zookeeper_secrets --opt type=none --opt device=/apps/sandbox/zookeeper/secrets --opt o=bind
# docker volume create --name sandbox_zookeeper_log --opt type=none --opt device=/apps/sandbox/zookeeper/log --opt o=bind
# docker volume create --name sandbox_logs --opt type=none --opt device=/apps/var/log --opt o=bind
---
version: '3.9'

services:
  #
  # Zookeeper Server
  #
  zookeeper:
    image: brijeshdhaker/zookeeper:3.7.1
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - /apps/sandbox/zookeeper:/zookeeper
      - ./conf/zookeeper:/opt/zookeeper/conf
      - ./conf/kerberos:/etc/kerberos
    environment:
      JVMFLAGS: "-Djava.security.auth.login.config=/opt/zookeeper/conf/jaas.conf -Djava.security.krb5.conf=/etc/kerberos/krb5.conf -Dzookeeper.requireClientAuthScheme=sasl"
      KRB5_CONFIG: "/etc/kerberos/krb5.conf"

#
volumes:
  sandbox_base_path:
    external: true
  sandbox_host_path:
    external: true
  sandbox_zookeeper_data:
    external: true
  sandbox_zookeeper_secrets:
    external: true
  sandbox_zookeeper_log:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net