#
# docker volume create --name sandbox_m2 --opt type=none --opt device=/apps/hostpath/.m2 --opt o=bind
# docker volume create --name sandbox_ivy2 --opt type=none --opt device=/apps/hostpath/.ivy2 --opt o=bind
#
# docker volume create --name sandbox_host_path --opt type=none --opt device=/apps/hostpath --opt o=bind
# docker volume create --name sandbox_base_path --opt type=none --opt device=/apps/sandbox --opt o=bind
# docker volume create --name sandbox_hadoop_324 --opt type=none --opt device=/opt/hadoop-3.2.4 --opt o=bind
# docker volume create --name sandbox_spark_312 --opt type=none --opt device=/opt/spark-3.1.2 --opt o=bind
# docker volume create --name sandbox_hive_312 --opt type=none --opt device=/opt/hive-3.1.2 --opt o=bind
# docker volume create --name sandbox_hbase_300 --opt type=none --opt device=/opt/hbase-3.0.0 --opt o=bind
# docker volume create --name sandbox_hbase_117 --opt type=none --opt device=/opt/hbase-1.1.7 --opt o=bind
#
# docker volume create --name sandbox_zeppelin --opt type=none --opt device=/apps/sandbox/zeppelin --opt o=bind
# docker volume create --name sandbox_zeppelin_notebook --opt type=none --opt device=/home/brijeshdhaker/IdeaProjects/zeppelin-notebooks --opt o=bind
#
---
#

version: '3.5'
services:
  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin
    env_file:
      - envs/docker_zeppelin.env
    ports:
      - "9080:8080"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_324:/opt/hadoop
      - sandbox_hbase_300:/opt/hbase
      - sandbox_hbase_117:/opt/hbase-client
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_312:/opt/spark
      - sandbox_zeppelin:/opt/zeppelin
      - sandbox_zeppelin_notebook:/opt/notebook
#      - sandbox_zeppelin_conf:/opt/zeppelin/conf
#      - sandbox_m2:/opt/zeppelin/.m2
#      - sandbox_ivy2:/opt/zeppelin/.ivy2

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_zeppelin:
    external: true
  sandbox_zeppelin_notebook:
    external: true
  sandbox_hbase_300:
    external: true
  sandbox_hbase_117:
    external: true
  sandbox_hive_312:
    external: true
  sandbox_spark_312:
    external: true
  sandbox_hadoop_324:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net