#
#
#
---
#

version: '3.5'
services:
  #
  # zookeeper standalone host
  #
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    hostname: zookeeper
    env_file:
      - docker-zookeeper/zookeeper.env
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    volumes:
      - "/apps/hostpath:/apps/hostpath"

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net