#
# docker volume create --name sandbox_apps_path --opt type=none --opt device=/apps --opt o=bind
# docker volume create --name sandbox_apps_path --opt type=none --opt device=/apps --opt o=bind
#
---
version: "3.9"

services:
  #
  # Kerberos Server
  #
  kdcserver:
    image: brijeshdhaker/kdcserver:22.04
    container_name: kdcserver
    hostname: kdcserver.sandbox.net
    volumes:
      - sandbox_apps_path:/apps
      - /dev/urandom:/dev/random      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - sandbox_krb5_stash:/etc/krb5kdc
      - sandbox_krb5_principal:/var/lib/krb5kdc/
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - ./envs/docker_kerberos.env
    ports:
      - "749:749"
      - "88:88/udp"

  #
  # Zookeeper Server
  #
  zookeeper:
    image: brijeshdhaker/zookeeper:3.7.1
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_zookeeper_371:/zookeeper
      - ./conf/zookeeper:/opt/zookeeper/conf
      - ./conf/kerberos:/etc/kerberos
    environment:
      JVMFLAGS: "-Djava.security.auth.login.config=/opt/zookeeper/conf/jaas.conf -Djava.security.krb5.conf=/etc/kerberos/krb5.conf"
      KRB5_CONFIG: "/etc/kerberos/krb5.conf"

  #
  # HDFS Cluster
  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/namenode/Dockerfile
    container_name: namenode
    hostname: namenode.sandbox.net
    restart: no
    ports:
      - "9870:9870"   # http
      - "9871:9871"   # https
      - "9000:9000"   # hdfs
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
    environment:
      CLUSTER_NAME: "docker-sandbox"
      MULTIHOMED_NETWORK: 2
    env_file:
      - envs/docker_hadoop.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/datanode/Dockerfile
    container_name: datanode
    hostname: datanode.sandbox.net
    ports:
      - "9864:9864"   # http
      - "9865:9865"   # https
      - "9866:9866"
    restart: always
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000"
    env_file:
      - envs/docker_hadoop.env

  #
  # YARN Cluster
  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager.sandbox.net
    restart: no
    ports:
      - "8088:8088"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    env_file:
      - envs/docker_yarn.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager.sandbox.net
    restart: no
    ports:
      - "8042:8042"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    environment:
      HADOOP_CONF_DIR: "/etc/yarn/conf"
      YARN_CONF_DIR: "/etc/yarn/conf"
      SERVICE_PRECONDITION: "resourcemanager.sandbox.net:8088"
    env_file:
      - envs/docker_yarn.env

  # YARN Timeline Server
  timelineserver:
    image: brijeshdhaker/hadoop-timelineserver:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/historyserver/Dockerfile
    container_name: timelineserver
    hostname: timelineserver.sandbox.net
    restart: always
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - envs/docker_yarn.env

  # MR History Server
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.2.4
    build:
      context: .
      dockerfile: docker-hadoop/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver.sandbox.net
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324_mapred:/mapred
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - envs/docker_yarn.env

  #
  # Mysql Server
  #
  mysqlserver:
    image: mysql/mysql-server:8.0.28
    container_name: mysqlserver
    hostname: mysqlserver.sandbox.net
    restart: always
    ports:
      - "3306:3306"
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_mysql_data:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    env_file:
      - ./envs/docker_mysql.env
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=p@SSW0rd --execute \"SHOW DATABASES;\""
      # test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  #
  # Hive Metastore
  #
  metastore:
    image: brijeshdhaker/hive:3.1.2
    container_name: metastore
    hostname: metastore.sandbox.net
    env_file:
      - ./envs/docker_hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "mysqlserver.sandbox.net:3306"
    ports:
      - "9083:9083"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos

  # Hive Server
  hiveserver:
    image: brijeshdhaker/hive:3.1.2
    container_name: hiveserver
    hostname: hiveserver.sandbox.net
    env_file:
      - ./envs/docker_hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://mysqlserver.sandbox.net:3306/metastore?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870 metastore.sandbox.net:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - sandbox_tez_092:/opt/tez
      - ./conf/hadoop/conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
      - ./conf/hive/conf/hive-env.sh:/opt/hive/conf/hive-env.sh
      - ./conf/kerberos:/etc/kerberos

  # Hive Tez UI
  hivetezui:
    image: brijeshdhaker/tezui:0.10.2
    container_name: hivetezui
    hostname: hivetezui.sandbox.net
    environment:
      KRB5_CONFIG: "/etc/kerberos/krb5.conf"
      SERVICE_PRECONDITION: "hiveserver.sandbox.net:10000 timelineserver.sandbox.net:8188"
    ports:
      - "9999:9999"
    volumes:
      - sandbox_apps_path:/apps
      - ./conf/kerberos:/etc/kerberos

  #
  # Hbase Cluster
  #
  hmaster:
    image: brijeshdhaker/hbase-master:3.0.0
    hostname: hmaster.sandbox.net
    container_name: hmaster
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181"
    env_file:
      - envs/docker_hbase.env
    ports:
      - "16000:16000"
      - "16010:16010"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hbase/hbase-env.sh:/opt/hbase/conf/hbase-env.sh
      - ./conf/hbase/hmaster-jaas.conf:/opt/hbase/conf/zk-jaas.conf

  #
  hregion:
    image: brijeshdhaker/hbase-regionserver:3.0.0
    hostname: hregion.sandbox.net
    container_name: hregion
    env_file:
      - envs/docker_hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181 hmaster.sandbox.net:16010"
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hbase/hbase-env.sh:/opt/hbase/conf/hbase-env.sh
      - ./conf/hbase/hregion-jaas.conf:/opt/hbase/conf/zk-jaas.conf
      - ./conf/hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml

  #
  # Spark History Server
  #
  sparkhistory:
    image: docker.io/brijeshdhaker/spark:3.4.0
    container_name: sparkhistory
    hostname: sparkhistory.sandbox.net
    environment:
      SPARK_WORKLOAD: HistoryServer
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    depends_on:
      - namenode
      - datanode
    ports:
      - "18080:18080"
    env_file:
      - ./envs/docker_spark312.env
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/spark/spark-env.sh:/opt/spark/conf/spark-env.sh
      - ./conf/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/ubuntu:22.04
    container_name: gateway
    hostname: gateway.sandbox.net
    restart: always
    command:
      - "/usr/sbin/sshd -D"
    ports:
      - "2222:22"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - sandbox_hbase_300:/opt/hbase
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_312:/opt/spark
      - sandbox_maven_363:/opt/maven-3.6.3
      - sandbox_zookeeper_371:/opt/zookeeper
      - ./conf/kerberos:/etc/kerberos
      - ./conf/profiles/brijeshdhaker.profile:/home/brijeshdhaker/brijeshdhaker.profile
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    env_file:
      - ./envs/docker_gateway.env

  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin.sandbox.net
    env_file:
      - ./envs/docker_zeppelin.env
    ports:
      - "9080:8080"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_324:/opt/hadoop
      - sandbox_hbase_300:/opt/hbase
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_312:/opt/spark
      - sandbox_zeppelin:/opt/zeppelin
      - sandbox_zeppelin_notebook:/opt/notebook
      - ./conf/kerberos:/etc/kerberos
#      - sandbox_zeppelin_conf:/opt/zeppelin/conf
#      - sandbox_m2:/opt/zeppelin/.m2
#      - sandbox_ivy2:/opt/zeppelin/.ivy2

#
#
#
volumes:
#
  sandbox_apps_path:
    external: true
#
  sandbox_krb5_stash:
    external: true
  sandbox_krb5_principal:
    external: true
#
  sandbox_maven_363:
    external: true
  sandbox_m2:
    external: true
  sandbox_ivy2:
    external: true
#
  sandbox_hadoop_324:
    external: true
  sandbox_hadoop_324_dfs:
    external: true
  sandbox_hadoop_324_mapred:
    external: true
  sandbox_hadoop_324_yarn:
    external: true
#
  sandbox_mysql_data:
    external: true
  sandbox_mysql_conf:
    external: true
#
  sandbox_zeppelin:
    external: true
  sandbox_zeppelin_notebook:
    external: true
#
  sandbox_zookeeper_371:
    external: true
#
  sandbox_hbase_300:
    external: true
#
  sandbox_hive_312:
    external: true
  sandbox_tez_092:
    external: true
#
  sandbox_spark_312:
    external: true


#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
