#
#
#
---
version: "3.9"

services:
  #
  # Kerberos Server
  kdcserver:
    image: brijeshdhaker/kdcserver:22.04
    container_name: kdcserver
    hostname: kdcserver.sandbox.net
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - /dev/urandom:/dev/random      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - sandbox_krb5_stash:/etc/krb5kdc
      - sandbox_krb5_principal:/var/lib/krb5kdc/
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    env_file:
      - ./envs/docker_kerberos.env
    ports:
      - "749:749"
      - "88:88/udp"

  # HDFS Sandbox
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/namenode/Dockerfile
    container_name: namenode
    hostname: namenode.sandbox.net
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hadoop/conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
      - ./conf/hadoop/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      CLUSTER_NAME: "docker-sandbox"
      MULTIHOMED_NETWORK: 2
    env_file:
      - ./envs/docker_hadoop334.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/datanode/Dockerfile
    container_name: datanode
    hostname: datanode.sandbox.net
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
      - ./conf/kerberos:/etc/kerberos
      - ./conf/hadoop/conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
      - ./conf/hadoop/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      CLUSTER_NAME: "docker-sandbox"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000"
    env_file:
      - ./envs/docker_hadoop334.env

  # YARN Sandbox
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager.sandbox.net
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
      - ./conf/yarn/fair-scheduler.xml:/opt/hadoop/etc/hadoop/fair-scheduler.xml
      - ./conf/yarn/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    env_file:
      - ./envs/docker_hadoop334.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager.sandbox.net
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    environment:
      SERVICE_PRECONDITION: "resourcemanager.sandbox.net:8088"
    env_file:
      - ./envs/docker_hadoop334.env

  # YARN Timeline Server
  timelineserver:
    image: brijeshdhaker/hadoop-timelineserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/historyserver/Dockerfile
    container_name: timelineserver
    hostname: timelineserver.sandbox.net
    restart: always
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - ./envs/docker_hadoop334.env

  # MR History Server
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.3.4
    build:
      context: .
      dockerfile: docker-hadoop-3.3.4/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver.sandbox.net
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_mr:/mapred
      - ./conf/kerberos:/etc/kerberos
    env_file:
      - ./envs/docker_hadoop334.env

  # Mysql Database Server
  mysqlserver:
    image: mysql/mysql-server:8.0.28
    container_name: mysqlserver
    hostname: mysqlserver.sandbox.net
    restart: always
    ports:
      - "3306:3306"
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_mysql_data:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    env_file:
      - ./envs/docker_mysql.env
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=p@SSW0rd --execute \"SHOW DATABASES;\""
      # test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # Hive Metastore
  metastore:
    image: brijeshdhaker/hive:3.1.2
    container_name: metastore
    hostname: metastore.sandbox.net
    env_file:
      - ./envs/docker_metastore.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "mysqlserver.sandbox.net:3306"
    ports:
      - "9083:9083"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf

  # Hive Server
  hiveserver:
    image: brijeshdhaker/hive:3.1.2
    container_name: hiveserver
    hostname: hiveserver.sandbox.net
    env_file:
      - ./envs/docker_hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://mysqlserver:3306/metastore?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false"
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870 metastore.sandbox.net:9083 mysqlserver.sandbox.net:3306"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_tez_010:/opt/tez
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf

  # Hive Tez UI
  hive-tezui:
    image: brijeshdhaker/tezui:0.10.2
    container_name: hivetezui
    hostname: hivetezui.sandbox.net
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870 metastore.sandbox.net:9083"
    ports:
      - "9999:9999"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf

  # Spark History Server
  sparkhistory:
    image: brijeshdhaker/spark:3.1.2-standalone
    container_name: sparkhistory
    hostname: sparkhistory.sandbox.net
    environment:
      SPARK_WORKLOAD: HistoryServer
      SERVICE_PRECONDITION: "namenode.sandbox.net:9000 namenode.sandbox.net:9870"
    depends_on:
      - namenode
      - datanode
    ports:
      - "18080:18080"
    env_file:
      - ./envs/docker_spark312.env
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - ./conf/kerberos:/etc/kerberos
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - ./conf/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/ubuntu:22.04
    container_name: gateway
    hostname: gateway.sandbox.net
    restart: always
    command:
      - "/usr/sbin/sshd -D"
    ports:
      - "2222:22"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_hbase_249:/opt/hbase
      - sandbox_hbase_117:/opt/hbase-client
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_340:/opt/spark
      - sandbox_maven_363:/opt/maven-3.6.3
      - ./conf/kerberos:/etc/kerberos
      - ./conf/gateway/sandbox.profile:/home/brijeshdhaker/sandbox.profile
      - ./conf/gateway/settings.xml:/home/brijeshdhaker/.m2/settings.xml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      CLUSTER_NAME: "docker-sandbox"
      ALLOW_ANONYMOUS_LOGIN: "yes"
      MULTIHOMED_NETWORK: 2
    env_file:
      - ./envs/docker_gateway.env


  # Zeppelin Notebook
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin.sandbox.net
    env_file:
      - ./envs/docker_zeppelin.env
    ports:
      - "9080:8080"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334:/opt/hadoop
      - sandbox_hbase_249:/opt/hbase
      - sandbox_hbase_117:/opt/hbase-client
      - sandbox_hive_312:/opt/hive
      - sandbox_spark_340:/opt/spark
      - sandbox_zeppelin:/opt/zeppelin
      - sandbox_zeppelin_notebook:/opt/notebook
#      - sandbox_zeppelin_conf:/opt/zeppelin/conf
#      - sandbox_m2:/opt/zeppelin/.m2
#      - sandbox_ivy2:/opt/zeppelin/.ivy2

#
#
#
volumes:
#
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
#
  sandbox_krb5_stash:
    external: true
  sandbox_krb5_principal:
    external: true
#
  sandbox_maven_363:
    external: true
  sandbox_m2:
    external: true
  sandbox_ivy2:
    external: true
#
  sandbox_hadoop_334:
    external: true
  sandbox_hadoop_334_dfs:
    external: true
  sandbox_hadoop_334_mr:
    external: true
  sandbox_hadoop_334_yarn:
    external: true
#
  sandbox_mysql_data:
    external: true
  sandbox_mysql_conf:
    external: true
#
  sandbox_zeppelin:
    external: true
  sandbox_zeppelin_notebook:
    external: true
#
  sandbox_hbase_249:
    external: true
  sandbox_hbase_117:
    external: true
#
  sandbox_hive_312:
    external: true
  sandbox_tez_010:
    external: true
#
  sandbox_spark_340:
    external: true


#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
