apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-configmap
data:
  environment: {{ .Values.environment | upper | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  message: "Hello World"
  {{- end }}
  {{- /* range $path, $_ := .Files.Glob "configs/*.yaml" -}}
  {{- base $path | nindent 2 }}: |-
  {{- $.Files.Get $path | nindent 4 }}
  {{- end */}}
  #
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  #
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }}
  #
  pizzaToppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{ $index }}: {{ $topping }}
    {{- end }}
  #
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  #
  {{- if eq .Values.environment "local" }}
  {{- (.Files.Glob "configs/application-local.yaml").AsConfig | nindent 2 -}}
  {{- else if eq .Values.environment "docker" }}
  {{- (.Files.Glob "configs/application-docker.yaml").AsConfig | nindent 2 -}}
  {{- else if eq .Values.environment "k8s" }}
  application.yaml: |- {{ .Files.Get "configs/application-k8s.yaml" | nindent 4 -}}
  {{- end }}