#
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-svc
  labels:
    date: 2025-04-06
spec:
  type: ExternalName
  externalName: mysqlserver.sandbox.net
#
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
#
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - name: mysql
        port: 3306
