apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-svc
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}

#
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

#
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  # by convention, use the name of the Service
  name: mysql-service-es
  # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: mysql-service
addressType: IPv4
ports:
  - name: mysql
    protocol: TCP
    port: 3306
endpoints:
  - addresses:
      - "192.168.9.128"
  - addresses:
      - "192.168.30.128"
#  - addresses:
#      - "10.0.1.1"

#
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP

#
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
subsets:
  - addresses:
      - ip: 192.168.30.128
      - ip: 192.168.9.128
    ports:
      - name: mysql
        port: 3306

#
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: schema-registry
      protocol: TCP
      port: 8081
      targetPort: 8081
#
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  # by convention, use the name of the Service
  name: kafka-service-es
  # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: kafka-service
addressType: IPv4
ports:
  - name: kafka
    protocol: TCP
    port: 9092
  - name: schema-registry
    protocol: TCP
    port: 8081
endpoints:
  - addresses:
      - "192.168.9.128"
  - addresses:
      - "192.168.30.128"
