apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: http-vsvc
spec:
  hosts:
    - "sbhttp.sandbox.net"
  gateways:
    - http-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9080
        host: springboot-app-svc

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: https-vsvc
spec:
  hosts:
    - "sbhttps.sandbox.net"
  gateways:
    - https-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 9080
            host: springboot-app-svc

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mtls-vsvc
spec:
  hosts:
    - "sbmtls.sandbox.net"
  gateways:
    - mtls-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 9080
            host: springboot-app-svc