
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm.fullname" . }}-volume
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /apps/sandbox

