/**
 * Author:  brijeshdhaker
 * Created: Sep 03, 2021
 */

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1001, 'Desktop', 100.00, 'ACTIVE', 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1002, 'Phone', 50.00, 'ACTIVE', 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1003, 'Head Phone', 10.00, 'ACTIVE', 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1004, 'Laptop', 140.00, 'ACTIVE', 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1005, 'Tablet', 60.00, 'ACTIVE', 20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1006, 'Camera', 150.00, 'ACTIVE', 20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1007, 'Keyboard', 5.00, 'ACTIVE', 30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into PRODUCTS (PRODUCT_ID, NAME, PRICE, STATUS, QUANTITY, ADD_TS, UPD_TS ) values
(1008, 'Drone', 100.00, 'ACTIVE', 40, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());