version: "3.5"
#
services:
#
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop-hive.env
    ports:
      - "9870:9870"
      - "9000:9000"

#
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
      - "9866:9866"

#
  hive-server:
    image: bde2020/hive:3.1.2-postgresql-metastore
    build:
      context: ""
      dockerfile: Dockerfile
    hostname: hive-server
    container_name: hive-server
    env_file:
      - hadoop-hive.env
    links:
      - hive-metastore  
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"

#
  hive-metastore:
    image: bde2020/hive:3.1.2-postgresql-metastore
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    links:
      - hive-metastore-postgresql  
    ports:
      - "9083:9083"
    
#
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.2
    build:
      context: ""
      dockerfile: Dockerfile
    hostname: hive-metastore-postgresql
    container_name: hive-metastore-postgresql
    ports:
      - "5432:5432"
    
#
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    hostname: presto-coordinator
    container_name: presto-coordinator
    ports:
      - "8080:8080"
    
#
volumes:
  namenode:
  datanode:
#
networks:
  default:
     name: mynet