#
server:
  port: 9080
  servlet:
    context-path: /api/v1
  http2:
    enabled: true
#
springdoc:
  api-docs:
    path: /api-docs
#
spring:
  #
#  config:
#    activate:
#      on-profile: default
  #
  application:
    name: bd-spring-module
  output.ansi.enabled: ALWAYS
  #
  security:
    oauth2:
      resourceserver:
        id: api://7f1cf4d7-ca24-47c2-bf17-61a8a796679e
        jwk:
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        jwt:
          issuer-uri: https://login.microsoftonline.com/da5ac8f7-13d6-46e7-815d-012b01123148/oauth2/v2.0/token
          audiences: api://7f1cf4d7-ca24-47c2-bf17-61a8a796679e
          authorization:
            group-to-authorities:
              "bcd99935-c922-4289-8bee-174369c157a5": SANDBOX_DEFAULT
              "3c19f1ea-f9e3-47d0-9d4a-aa97c29d0867": SANDBOX_ADMIN
              "ebddcd37-20a5-4272-ae8d-7e90be4a7e46": SANDBOX_OPERATE
              "6489408e-121a-4d49-bb45-dbe074435179": SANDBOX_RW
              "29132c43-c263-4015-9f42-9c848d9b2f3b": SANDBOX_RO
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/da5ac8f7-13d6-46e7-815d-012b01123148/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: 7f1cf4d7-ca24-47c2-bf17-61a8a796679e
            client-secret: sVy8Q~jmLAlU3N9viydtvGBBGb5WL2XpBtCq_aqU
            scope:
              - openid
              - email
              - profile
  #
  datasource:
    name: SANDBOXDB
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:SANDBOXDB;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;mode=mysql;
    url: jdbc:h2:file:/apps/sandbox/h2/SANDBOXDB;mode=mysql;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  #
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  #
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:schema.sql
#      data-locations: classpath*:data.sql
  #
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      use-new-id-gnerator-mappings: false
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  #
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.yml
    contexts: h2
    parameters:
      textColumnType: TEXT
  #
  cache:
    jcache:
      config: classpath:ehcache.xml
  #
  kafka:
    transaction-topic: transaction-avro-topic
    bootstrap-servers:
      - kafkabroker.sandbox.net:9092
    properties:
      # Schema Registry Connection parameter
      schema.registry.url: http://schemaregistry.sandbox.net:8081
      schema.registry.ssl.keystore.location: /apps/security/ssl/clients.keystore.jks
      schema.registry.ssl.keystore.password: confluent
      schema.registry.ssl.key.password: confluent
      schema.registry.ssl.keystore.type: JKS
      schema.registry.ssl.truststore.location: /apps/security/ssl/clients.truststore.jks
      schema.registry.ssl.truststore.password: confluent
    consumer:
      properties:
        specific.avro.reader: false
        # spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        # spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: sb-sandbox-cg
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    producer:
      #properties:
      #  allow.auto.create.topics: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
#
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
#
logging:
  level:
    root: info
    org.springframework.kafka: error
    org.springframework.transaction: trace