flink:
  hadoop:
    fs:
      default-scheme: s3a://warehouse-flink/
      s3a:
        access:
          key: admin
        impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        aws:
          credentials:
            provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
        secret:
          key: password
        path:
          style:
            access: true
        endpoint: http://minio.sandbox.net:9010
env:
  java:
    opts:
      jobmanager: -Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=true -Djava.security.krb5.kdc=kdcserver.sandbox.net -Djava.security.krb5.realm=SANDBOX.NET -Djava.security.auth.login.config=/apps/security/jaas/kafkaclients-jaas.conf
      all: --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
      taskmanager: -Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=true -Djava.security.krb5.kdc=kdcserver.sandbox.net -Djava.security.krb5.realm=SANDBOX.NET -Djava.security.auth.login.config=/apps/security/jaas/kafkaclients-jaas.conf
  log:
    max: 5
    dir: /apps/var/logs/flink/
    level: INFO
jobmanager:
  rpc:
    address: flink-jobmanager
    port: 6123
  execution:
    failover-strategy: region
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
s3:
  secret-key: password
  access-key: admin
  endpoint: http://minio.sandbox.net:9010
  path:
    style:
      access: true
io:
  tmp:
    dirs: /tmp
execution:
  checkpointing:
    savepoint-dir: s3a://warehouse-flink/execution/savepoints
    interval: 10s
    dir: s3a://warehouse-flink/execution/
parallelism:
  default: 4
state:
  backend:
    type: hashmap
    incremental: false
    fs:
      checkpointdir: s3a://warehouse-flink/fs/checkpoints
  savepoints:
    dir: s3a://warehouse-flink/state/savepoints
  checkpoints:
    dir: s3a://warehouse-flink/state/checkpoints
fs:
  default-scheme: s3a://warehouse-flink/
  s3a:
    access:
      key: admin
    impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    aws:
      credentials:
        provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    secret:
      key: password
    path:
      style:
        access: true
    buffer:
      dir: /tmp
    endpoint: http://minio.sandbox.net:9010
taskmanager:
  memory:
    process:
      size: 1728m
  host: flink-taskmanager
  numberOfTaskSlots: 8
  bind-host: 0.0.0.0
web:
  cancel:
    enable: true
  submit:
    enable: true
rest:
  bind-address: 0.0.0.0
  address: flink-jobmanager
  profiling:
    enabled: true
  flamegraph:
    enabled: true
security:
  kerberos:
    login:
      principal: brijeshdhaker@SANDBOX.NET
      keytab: /apps/security/keytabs/users/brijeshdhaker.keytab
      use-ticket-cache: false
blob:
  server:
    port: '6124'
query:
  server:
    port: '6125'
