# docker volume create --name sandbox_flink_data --opt type=none --opt device=/apps/sandbox/flink/data --opt o=bind

#
# docker compose -f bd-docker-sandbox/docker-compose.yaml up -d
# docker compose -f bd-docker-sandbox/docker-compose.yaml down
#

#
# docker compose -f bd-docker-sandbox/dc-flink-cluster.yaml up -d
# docker compose -f bd-docker-sandbox/dc-flink-cluster.yaml down
#

version: "3.9"

services:
  #
  #
  #
  flink-jobmanager:
    image: brijeshdhaker/flink:1.17.2
    container_name: flink-jobmanager
    command: "jobmanager.sh start-foreground"
    expose:
      - "6123"
    ports:
      - 8881:8081
    healthcheck:
      test: curl -f http://flink-jobmanager:8081 || exit 1
      retries: 20
      interval: 10s
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_334:/opt/hadoop
      - ../bd-hadoop-sandbox/conf/hadoop/client:/opt/hadoop/etc/hadoop
      - ./conf/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - sandbox_flink_data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop


  #
  #
  #
  flink-taskmanager:
    image: brijeshdhaker/flink-taskmanager:1.17.2
    container_name: flink-taskmanager
    depends_on:
      flink-jobmanager:
        condition: service_healthy
    command: "taskmanager.sh start-foreground"
    expose:
      - "6121"
      - "6122"
    healthcheck:
      test: echo $HOSTNAME || exit 1
      retries: 20
      interval: 10s
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_334:/opt/hadoop
      - ../bd-hadoop-sandbox/conf/hadoop/client:/opt/hadoop/etc/hadoop
      - ./conf/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - sandbox_flink_data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop

#
volumes:
  sandbox_apps_path:
    external: true
  #
  sandbox_flink_data:
    external: true
  #
  sandbox_hadoop_334:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net