#

#
# docker volume create --name sandbox_apps_path --opt type=none --opt device=/apps --opt o=bind
# docker volume create --name sandbox_security_secrets --opt type=none --opt device=/apps/security/ssl --opt o=bind
#
# docker volume create --name sandbox_krb5_stash --opt type=none --opt device=/apps/sandbox/kerberos/stash --opt o=bind
# docker volume create --name sandbox_krb5_principal --opt type=none --opt device=/apps/sandbox/kerberos/principal --opt o=bind
#
# docker volume create --name sandbox_zookeeper334_data --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop334/data --opt o=bind
# docker volume create --name sandbox_zookeeper334_log --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop334/log --opt o=bind
#
# docker volume create --name sandbox_hadoop_334 --opt type=none --opt device=/opt/hadoop-3.3.4 --opt o=bind
# docker volume create --name sandbox_hadoop_334_dfs --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/dfs --opt o=bind
# docker volume create --name sandbox_hadoop_334_yarn --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/yarn --opt o=bind
# docker volume create --name sandbox_hadoop_334_mapred --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/mapred --opt o=bind
#
# docker volume create --name sandbox_spark_350 --opt type=none --opt device=/opt/spark-3.5.0 --opt o=bind
# docker volume create --name sandbox_hive_313 --opt type=none --opt device=/opt/hive-3.1.3 --opt o=bind
# docker volume create --name sandbox_tez_102 --opt type=none --opt device=/opt/tez-0.10.2 --opt o=bind
# docker volume create --name sandbox_hbase_246 --opt type=none --opt device=/opt/hbase-2.4.6 --opt o=bind
# docker volume create --name sandbox_hbase_117 --opt type=none --opt device=/opt/hbase-1.1.7 --opt o=bind
# docker volume create --name sandbox_flink_112 --opt type=none --opt device=/opt/flink-1.12.2 --opt o=bind
#
---
version: "3.9"

include:
  - dc-zookeeper.yml
  - dc-hadoop-cluster.yml

services:
  #
  # Hbase Cluster
  #
  hmaster:
    image: brijeshdhaker/hbase-master:2.4.6
    hostname: hmaster.sandbox.net
    container_name: hmaster
    healthcheck:
      test: curl -f http://hmaster.sandbox.net:16010 || exit 1
      retries: 20
      interval: 10s
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181"
    env_file:
      - envs/docker_hbase.env
      - envs/docker_clients.env
    ports:
      - "16000:16000"
      - "16010:16010"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_334:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop

  #
  hregion:
    image: brijeshdhaker/hbase-regionserver:2.4.6
    hostname: hregion.sandbox.net
    container_name: hregion
    healthcheck:
      test: curl -f http://hregion.sandbox.net:16030 || exit 1
      retries: 20
      interval: 10s
    env_file:
      - envs/docker_hbase.env
      - envs/docker_clients.env
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181 hmaster.sandbox.net:16010"
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_334:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop

#
#
#
volumes:
  #
  sandbox_hadoop_334:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
