#
# docker volume create --name sandbox_security_secrets --opt type=none --opt device=/apps/security/ssl --opt o=bind
# docker volume create --name sandbox_zookeeper334_data --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop334/data --opt o=bind
# docker volume create --name sandbox_zookeeper334_log --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop334/log --opt o=bind
# docker volume create --name sandbox_kafka334_data --opt type=none --opt device=/apps/sandbox/kafka/hadoop334/data --opt o=bind
# docker volume create --name sandbox_kafka334_log --opt type=none --opt device=/apps/sandbox/kafka/hadoop334/log --opt o=bind
#
---

# version: "3.9"

#
include:
  - path: ../bd-docker-sandbox/dc-zookeeper.yml

#
services:

  ## Kafka Broker
  kafka-broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka-broker.sandbox.net
    container_name: kafka-broker
    # restart: on-failure
    healthcheck:
      test: nc kafka-broker.sandbox.net 9092 || exit 1
      retries: 20
      interval: 10s
    depends_on:
      kdcserver:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
      - 19092:19092
      - 19093:19093
      - 19094:19094
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_kafka334_data:/var/lib/kafka/data
      - sandbox_kafka334_log:/var/lib/kafka/log
      - sandbox_security_secrets:/etc/kafka/secrets
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      KRB5_CONFIG: "/etc/krb5.conf"
      KAFKA_BROKER_ID: "1"
      KAFKA_BROKER_RACK: "R1"
      KAFKA_JMX_PORT: 9991
      #
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.sandbox.net:2182'
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /apps/security/ssl/kafka-broker.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /apps/security/ssl/kafka-broker.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_ZOOKEEPER_SET_ACL: 'true'

      # KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      # https://docs.confluent.io/platform/current/kafka/multi-node.html#configure-multi-node-environment
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, SASL_PLAINTEXT://0.0.0.0:19092, SASL_SSL://0.0.0.0:19093, SSL://0.0.0.0:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker.sandbox.net:9092,SASL_PLAINTEXT://kafka-broker.sandbox.net:19092,SASL_SSL://kafka-broker.sandbox.net:19093,SSL://kafka-broker.sandbox.net:19094
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      #
      ## Kerberos / GSSAPI Authentication mechanism
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,GSSAPI
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      #
      ## Listener INTERNAL Configuration
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="admin" \
        password="admin-secret" \
        user_admin="admin-secret" \
        user_mds="mds-secret";
      #
      ## Listener TOKEN Configuration
      KAFKA_LISTENER_NAME_SASL__SSL_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_LISTENER_NAME_SASL__SSL_GSSAPI_SASL_JAAS_CONFIG: |
        com.sun.security.auth.module.Krb5LoginModule required \
        debug=true \
        useKeyTab=true \
        storeKey=true \
        keyTab="/apps/security/keytabs/services/kafka-broker.keytab" \
        principal="kafka/kafka-broker.sandbox.net@SANDBOX.NET";
      #
      ## SSL Additions
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker.keystore.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker-keystore-creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker-sslkey-creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker-truststore-creds
      # To enable the broker to authenticate clients (two-way authentication)
      KAFKA_SSL_CLIENT_AUTH: "required"
      # The endpoint identification algorithm used by clients to validate server host name.
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      #
      KAFKA_LISTENER_NAME_SASL_SSL_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([a-zA-Z0-9.]*).*$$/$$1/ , DEFAULT
      KAFKA_LISTENER_NAME_SSL_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([a-zA-Z0-9.]*).*$$/$$1/ , DEFAULT
      ##
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/apps/security/jaas/kafka-broker-jaas.conf
        -Djava.security.krb5.conf=/etc/krb5.conf
        -Dsun.security.krb5.debug=false
        -Dssl.keystore.location=/apps/security/ssl/kafka-broker.keystore.p12
        -Dssl.keystore.password=confluent
        -Dssl.key.password=confluent
        -Dssl.truststore.location=/apps/security/ssl/kafka-broker.truststore.jks
        -Dssl.truststore.password=confluent
      #
      ## Log4J
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,org.apache.kafka=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: "INFO, authorizerAppender"
      KAFKA_LOG4J_ADDITIVITY_KAFKA_AUTHORIZER_LOGGER: "false"
      ##
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: https://schema-registry.sandbox.net:8081
      #KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker.sandbox.net:19093
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    extra_hosts:
      - "thinkpad.sandbox.net:172.18.0.1"

  #
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry.sandbox.net
    container_name: schema-registry
    depends_on:
      - kafka-broker
    ports:
      - "8081:8081"
    healthcheck:
      test: nc schema-registry.sandbox.net 8081 || exit 1
      retries: 20
      interval: 10s
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/schema-registry/secrets
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      KRB5_CONFIG: "/etc/krb5.conf"
      JAVA_OPTS: |
        -Djava.security.krb5.conf=/etc/krb5.conf 
        -Dsun.security.krb5.debug=false
        -Djavax.net.ssl.keyStore=/apps/security/ssl/schema-registry.keystore.jks
        -Djavax.net.ssl.keyStorePassword=confluent
        -Djavax.net.ssl.trustStore=/apps/security/ssl/schema-registry.truststore.jks
        -Djavax.net.ssl.trustStorePassword=confluent
      #
      SCHEMA_REGISTRY_OPTS: "-Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=false"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry.sandbox.net
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker.sandbox.net:19093'
      # Configure SASL_SSL if SSL encryption is enabled, otherwise configure SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: GSSAPI
      SCHEMA_REGISTRY_KAFKASTORE_SASL_KERBEROS_SERVICE_NAME: kafka
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required
        useKeyTab=true
        storeKey=true
        useTicketCache=false
        keyTab="/apps/security/keytabs/services/schema-registry.keytab"
        principal="schema-registry/schema-registry.sandbox.net@SANDBOX.NET";
      #
      SCHEMA_REGISTRY_LISTENERS: https://0.0.0.0:8081
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      #
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /apps/security/ssl/schema-registry.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /apps/security/ssl/schema-registry.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: confluent
      SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      #
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /apps/security/ssl/schema-registry.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /apps/security/ssl/schema-registry.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: confluent
      SCHEMA_REGISTRY_SSL_CLIENT_AUTH: "true"
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "https"
    extra_hosts:
      - "thinkpad.sandbox.net:172.18.0.1"

  #
  kafkaclient:
    image: brijeshdhaker/kafka-clients:7.5.0
    hostname: kafkaclient.sandbox.net
    container_name: kafkaclient
    restart: on-failure
    command: sleep infinity
    volumes:
      - sandbox_apps_path:/apps
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      KRB5_CONFIG: "/etc/krb5.conf"
    extra_hosts:
      - "thinkpad.sandbox.net:172.18.0.1"

#
# Docker Volumes
#
volumes:
  #
  sandbox_apps_path:
    external: true
  #
  sandbox_security_secrets:
    external: true

#
# Docker Networks
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net