#
# Use root/paSSW0rd user/password credentials
#
# docker volume create --name sandbox_apps_path --opt type=none --opt device=/apps --opt o=bind
# docker volume create --name sandbox_mysql_data --opt type=none --opt device=/apps/sandbox/mysql/data --opt o=bind
#
# docker compose -f bd-docker-sandbox/docker-compose.yml up -d mysqlserver
# docker compose -f bd-docker-sandbox/docker-compose.yml down mysqlserver
#
# docker exec -it mysqlserver mysql --user=root --password=paSSW0rd --host=localhost
# docker exec -it mysqlserver mysql --user=root --password=paSSW0rd --host=mysqlserver.sandbox.net --database=SANDBOXDB
#
---


services:
  #
  # Mysql Server
  #
  mysqlserver:
    image: mysql:8.0.33
    container_name: mysqlserver
    hostname: mysqlserver.sandbox.net
    restart: always
    ports:
      - "3306:3306"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_mysql_data:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    secrets:
      - mysql-root-password
    env_file:
      - ./conf/mysql/envvars
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ADMIN_PASSWORD --execute \"SHOW DATABASES;\""
      # test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ADMIN_PASSWORD']
      timeout: 20s
      retries: 10
      interval: 10s
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"
      
  #
  #
  #
#  adminer:
#    image: adminer
#    restart: always
#    hostname: adminer
#    container_name: adminer
#    ports:
#      - 8080:8080

#
secrets:
  mysql-root-password:
    file: ./conf/mysql/password.txt

#
volumes:
  sandbox_apps_path:
    external: true
  sandbox_mysql_data:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net