#
# docker volume create --name sandbox_kafka_secrets --opt type=none --opt device=/apps/sandbox/kafkabroker/secrets --opt o=bind
# docker volume create --name sandbox_kafka_data --opt type=none --opt device=/apps/sandbox/kafkabroker/data --opt o=bind
# docker volume create --name sandbox_kafka_log --opt type=none --opt device=/apps/sandbox/kafkabroker/log --opt o=bind
#
---
version: "3.9"

services:
  #
  # Zookeeper Server
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    healthcheck:
      test: curl -f http://zookeeper.sandbox.net:8080/commands || exit 1
      retries: 20
      interval: 10s
    ports:
      - "2181:2181"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/zookeeper/secrets
      - /apps/sandbox/zookeeper/data:/var/lib/zookeeper/data
      - /apps/sandbox/zookeeper/log:/var/lib/zookeeper/log
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_UNSIGNED: "true"

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net