#
# spark-shell --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.3
# spark-shell --packages org.apache.iceberg:iceberg-spark-runtime-3.1_2.12-0.13.1
#
---
version: "3.9"

include:
  - dc-hadoop-cluster.yaml

services:
  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/ubuntu:22.04
    container_name: gateway
    hostname: gateway.sandbox.net
    healthcheck:
      test: nc -vz gateway.sandbox.net 22 || exit 1
      retries: 20
      interval: 10s
    restart: always
    command:
      - "/usr/sbin/sshd -D"
    ports:
      - "2222:22"
      - "4040:4040"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_311:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop
      - sandbox_hbase_246:/opt/hbase
      - ./conf/hbase/client:/opt/hbase/conf
      - sandbox_hive_313:/opt/hive
      - ./conf/hive/client/hive-site.xml:/opt/hive/conf/hive-site.xml
      - sandbox_spark_312:/opt/spark
      - sandbox_flink_112:/opt/flink
      - sandbox_maven_363:/opt/maven-3.6.3

    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    env_file:
      - ./envs/docker_clients.env

  #
  # Zeppelin Notebook
  #
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin.sandbox.net
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    env_file:
      - ./envs/docker_clients.env
    ports:
      - "9080:8080"
      - "9081:8081"
    healthcheck:
      test: echo $HOSTNAME || exit 1
      retries: 20
      interval: 10s
    volumes:
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - sandbox_apps_path:/apps
      - /apps/sandbox/zeppelin/conf:/opt/zeppelin/conf
      - sandbox_zeppelin_notebook:/opt/notebook
      - sandbox_spark_312:/opt/spark
      - sandbox_hadoop_311:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop
      - sandbox_hive_313:/opt/hive
      - ./conf/hive/client/hive-site.xml:/opt/hive/conf/hive-site.xml
      - sandbox_hbase_246:/opt/hbase
      - ./conf/hbase/client:/opt/hbase/conf
      - sandbox_flink_112:/opt/flink


#
#
#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_security_secrets:
    external: true
  #
  sandbox_maven_363:
    external: true
  sandbox_m2:
    external: true
  sandbox_ivy2:
    external: true
  #
  sandbox_zeppelin_conf:
    external: true
  sandbox_zeppelin_notebook:
    external: true
  #
  sandbox_hbase_246:
    external: true
  sandbox_hbase_117:
    external: true
  #
  sandbox_hive_313:
    external: true
  sandbox_tez_091:
    external: true
  #
  sandbox_spark_312:
    external: true
  #
  sandbox_flink_112:
    external: true


#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
