#
# docker compose -f bd-docker-sandbox/docker-compose.yaml up -d
# docker compose -f bd-docker-sandbox/docker-compose.yaml down
#
---
version: "3.9"

include:
  - path: ../bd-hadoop-sandbox/dc-minio.yml
  - path: ../bd-hadoop-sandbox/dc-mysqlserver.yml

#
services:
  #
  notebook:
    image: brijeshdhaker/notebook:3.5.2
    container_name: notebook
    hostname: notebook.sandbox.net
    depends_on:
      - minio
      - mysqlserver
    #user: root
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - sandbox_apps_path:/apps
      - /apps/sandbox/notebooks:/home/jovyan/work/notebooks
      - ./conf/spark/conf:/usr/local/spark/conf
    environment:
      GRANT_SUDO: yes
      PYARROW_IGNORE_TIMEZONE: 1
  #    env_file:
  #      - ./envs/docker_clients.env

  #
  # Gateway Node
  #
  gateway:
    image: brijeshdhaker/ubuntu:22.04
    container_name: gateway
    hostname: gateway.sandbox.net
    healthcheck:
      test: nc -vz gateway.sandbox.net 22 || exit 1
      retries: 20
      interval: 10s
    restart: always
    command:
      - "/usr/sbin/sshd -D"
    ports:
      - "2222:22"
    volumes:
      - sandbox_apps_path:/apps
#      - sandbox_hadoop_334:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop
      - sandbox_hbase_246:/opt/hbase
      - ./conf/hbase/client:/opt/hbase/conf
      - sandbox_hive_313:/opt/hive
      - ./conf/hive/client/hive-site.xml:/opt/hive/conf/hive-site.xml
      - /opt/spark-3.4.1:/opt/spark
      - ./conf/spark/conf:/opt/spark/conf
      - sandbox_flink_112:/opt/flink
      - /opt/maven-3.6.3:/opt/maven-3.6.3
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    env_file:
      - ./envs/docker_clients.env
    extra_hosts:
      - "thinkpad.sandbox.net:172.18.0.1"

#
#
#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_minio_data:
    external: true
  sandbox_security_secrets:
    external: true
  #
  sandbox_maven_363:
    external: true
  sandbox_m2:
    external: true
  sandbox_ivy2:
    external: true
  #
  sandbox_zeppelin_conf:
    external: true
  sandbox_zeppelin_notebook:
    external: true
  #
  sandbox_hadoop_334:
    external: true
  #
  sandbox_hbase_246:
    external: true
  sandbox_hbase_117:
    external: true
  #
  sandbox_hive_313:
    external: true
  sandbox_tez_102:
    external: true
  #
  sandbox_spark_350:
    external: true
  #
  sandbox_flink_112:
    external: true


#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
