#
# docker build -t brijeshdhaker/mc:2024.03.02 -f bd-hadoop-sandbox/docker-minio/mc/Dockerfile .
# docker push brijeshdhaker/mc:2024.03.02
#

#
FROM minio/minio:latest

MAINTAINER "Brijesh K Dhaker <brijeshdhaker@gmail.com>"
#
RUN microdnf install wget
