#
#
#

version: '3.1'
services:
  #
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
#    restart: always
    ports:
      - "5432:5432"
    entrypoint: /init-setup.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
      PGDATA: /apps/hostpath/postgres/data
    volumes:
      - /apps/hostpath:/apps/hostpath
  #