kafka:
  transaction-topic: transaction-avro-topic
topic:
  name: users
  partitions-num: 1
  replication-factor: 1
server:
  port: 9080
spring:
  application:
    name: bd-spring-module
  output.ansi.enabled: ALWAYS
  #
  datasource:
    name: SANDBOXDB
    username: mysqladmin
    password: mysqladmin
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlserver.sandbox.net:3306/SANDBOXDB?zeroDateTimeBehavior=CONVERT_TO_NULL
  #
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-gnerator-mappings: false
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  #
  kafka:
    transaction-topic: transaction-json-topic
    bootstrap-servers:
      - kafkabroker.sandbox.net:9092
    properties:
      # Schema Registry Connection parameter
      schema.registry.url: http://schemaregistry.sandbox.net:8081
      schema.registry.ssl.keystore.location: /apps/security/ssl/clients.keystore.jks
      schema.registry.ssl.keystore.password: confluent
      schema.registry.ssl.key.password: confluent
      schema.registry.ssl.keystore.type: JKS
      schema.registry.ssl.truststore.location: /apps/security/ssl/clients.truststore.jks
      schema.registry.ssl.truststore.password: confluent
#    listener:
#      immediate-stop: true
#      ack-mode: RECORD  #BATCH RECORD MANUAL_IMMEDIATE MANUAL
#      async-acks: true
    consumer:
      properties:
        specific.avro.reader: false
        spring.json.trusted.packages: "*"
        # spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        # spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: sb-sandbox-json-cg
      auto-offset-reset: earliest
      enable.auto.commit: false
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    producer:
      properties:
        allow.auto.create.topics: false
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    template:
      default-topic:
  #
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
  #
#  liquibase:
#    enabled: true
#    change-log: classpath:liquibase/master.yml
#    contexts: h2
#    parameters:
#      textColumnType: TEXT
#
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
#
logging:
  level:
    root: info
    org.springframework.kafka: debug