blob:
  server:
    port: '6124'
env:
  java:
    opts:
      jobmanager: -Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=true -Djava.security.krb5.kdc=kdcserver.sandbox.net -Djava.security.krb5.realm=SANDBOX.NET -Djava.security.auth.login.config=/apps/security/jaas/kafkaclients-jaas.conf
      all: --add-exports=java.base/sun.net.util=ALL-UNNAMED --add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
      taskmanager: -Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=true -Djava.security.krb5.kdc=kdcserver.sandbox.net -Djava.security.krb5.realm=SANDBOX.NET -Djava.security.auth.login.config=/apps/security/jaas/kafkaclients-jaas.conf
rest:
  flamegraph:
    enabled: true
  bind-address: 0.0.0.0
  address: flink-jobmanager
  profiling:
    enabled: true
jobmanager:
  execution:
    failover-strategy: region
  rpc:
    address: flink-jobmanager
    port: 6123
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
state:
  savepoints:
    dir: file:///apps/sandbox/flink/savepoints
  backend:
    type: hashmap
    incremental: false
  checkpoints:
    dir: file:///apps/sandbox/flink/checkpoints
security:
  kerberos:
    login:
      use-ticket-cache: false
      contexts: Client,KafkaClient
      principal: flink@SANDBOX.NET
      keytab: /apps/security/keytabs/users/flink.keytab
  delegation:
    tokens:
      enabled: true
query:
  server:
    port: '6125'
s3:
  secret-key: 9u8TCmTtg9VyCVzgfDl6LvgcDd84DaM4h43bg1Bs
  endpoint: http://minio.sandbox.net:9010
  path-style: true
  access-key: ffaJ6a2MOj8mZ5lI3P6h
  path:
    style:
      access: true
io:
  tmp:
    dirs: /tmp
taskmanager:
  host: flink-taskmanager
  numberOfTaskSlots: 8
  memory:
    process:
      size: 1728m
  bind-host: 0.0.0.0
parallelism:
  default: 4
web:
  cancel:
    enable: true
  submit:
    enable: true
