blob:
  server:
    port: '6124'
rest:
  flamegraph:
    enabled: true
  bind-address: 0.0.0.0
  address: flink-jobmanager
  profiling:
    enabled: true
jobmanager:
  execution:
    failover-strategy: region
  rpc:
    address: flink-jobmanager
    port: 6123
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
state:
  savepoints:
    dir: file:///apps/sandbox/flink/savepoints
  backend:
    type: hashmap
    incremental: false
  checkpoints:
    dir: file:///apps/sandbox/flink/checkpoints
query:
  server:
    port: '6125'
s3:
  secret-key: zjd8T0hXFGtfemVQ6AH3yBAPASJNXNbVSx5iddqG
  endpoint: http://minio.sandbox.net:9010
  path-style: true
  access-key: pgm2H2bR7a5kMc5XCYdO
  path:
    style:
      access: true
io:
  tmp:
    dirs: /tmp
taskmanager:
  host: flink-taskmanager
  numberOfTaskSlots: 8
  memory:
    process:
      size: 1728m
  bind-host: 0.0.0.0
parallelism:
  default: 4
web:
  cancel:
    enable: true
  submit:
    enable: true
