---
# Source: bd-spring-module/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
  labels:
    date: 2025-04-20
    helm.sh/chart: bd-spring-module-0.1.0
    app.kubernetes.io/name: springboot-app
    app.kubernetes.io/instance: bd-spring-module
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: springboot-app
    app.kubernetes.io/instance: bd-spring-module

#
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

#
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP

#
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: schema-registry
      protocol: TCP
      port: 8081
      targetPort: 8081
#
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  # by convention, use the name of the Service
  name: mysql-service-es
  # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: mysql-service
addressType: IPv4
ports:
  - name: mysql
    protocol: TCP
    port: 3306
endpoints:
  - addresses:
      - "192.168.9.128"
  - addresses:
      - "192.168.30.128"
#  - addresses:
#      - "10.0.1.1"

#
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  # by convention, use the name of the Service
  name: kafka-service-es
  # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: kafka-service
addressType: IPv4
ports:
  - name: kafka
    protocol: TCP
    port: 9092
  - name: schema-registry
    protocol: TCP
    port: 8081
endpoints:
  - addresses:
      - "192.168.9.128"
  - addresses:
      - "192.168.30.128"
---
# Source: bd-spring-module/templates/services.yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-docker
  labels:
    date: 2025-04-06
subsets:
  - addresses:
      - ip: 192.168.30.128
      - ip: 192.168.9.128
    ports:
      - name: mysql
        port: 3306

#
