---
# Source: bd-spring-module/templates/volumes-claims.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-app-pvc
  labels:
    date: 2025-04-20
    helm.sh/chart: bd-spring-module-0.1.0
    app.kubernetes.io/name: springboot-app
    app.kubernetes.io/instance: bd-spring-module
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: sb-apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
