# docker-compose build
# docker-compose up -d
# docker-compose scale nodemanager=X; # X=integer number --> allows to add more nodes to the hadoop cluster for testing

version: '3'
services:
  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
#    volumes:
#      - /apps/hostpath/mongo:/data/db

#      
  namenode:
    image: hadoop:3.2.0
    container_name: namenode
    ports:
      - "9000:9000"
      - "9870:9870"
    command: /usr/local/bin/start-namenode.sh
    hostname: nodename.hadoop.svc.cluster.local
    volumes:
      - /apps/hostpath:/apps/hostpath
#
  datanode:
    image: hadoop:3.2.0
    command: hdfs datanode
    ports:
      - "9864:9864" 
      - "9866:9866"
    links:
      - namenode
    hostname: datanode.hadoop.svc.cluster.local
    volumes:
      - /apps/hostpath:/apps/hostpath
#
  secondarynamenode:
    image: hadoop:3.2.0
    container_name: secondarynamenode
    command: hdfs secondarynamenode
    ports:
      - "9868:9868"
    links:
      - namenode
    hostname: secondarynamenode.hadoop.svc.cluster.local
#    
  yarn:
    image: hadoop:3.2.0
    container_name: yarn
    command: start-yarn-historyserver.sh
    ports:
      - "8088:8088"
      - "8042:8042"
      - "8050:8050"
      - "19888:19888"
      - "10020:10020"
    links:
      - namenode
      - datanode
    hostname: yarn.hadoop.svc.cluster.local
#    
  nodemanager:
    image: hadoop:3.2.0
    command: yarn nodemanager
    hostname: nodemanager.hadoop.svc.cluster.local
    ports:
      - "8042" 
    links:
      - namenode
      - datanode
      - yarn
#          
  hadoop-cluster-example:
    image: hadoop-cluster-example:latest
    container_name: hadoop-cluster-example
    links:
      - mongo
      - yarn 
      - namenode
    volumes:
      - /apps/hostpath:/apps/hostpath
