FROM nginx

MAINTAINER "Brijesh K Dhaker <brijeshdhaker@gmail.com>"

COPY docker-hadoop/nodemanager/default.conf /etc/nginx/conf.d/default.conf
COPY docker-hadoop/nodemanager/materialize.min.css /data/bde-css/materialize.min.css
COPY docker-hadoop/nodemanager/bde-hadoop.css /data/bde-css/bde-hadoop.css
