#!/usr/bin/env bash

flavor=$(cat ./sandbox-flavor)
if [ "$flavor" == "hdf" ]; then
 name="sandbox-hdf-standalone-cda-ready"
 hostname="sandbox-hdf.hortonworks.com"
elif [ "$flavor" == "hdp" ]; then
 name="sandbox-hdp-security"
 hostname="sandbox-hdp.hortonworks.com"
fi

version=$(docker images | grep $name  | awk '{print $2}');
image="hortonworks/sandbox-hdp-security:3.0"
# image="hortonworks/sandbox-hdp:3.0.1"
# image="sandbox-hdp-311:latest"
# Create cda docker network
# docker network create cda

#
# Deploy the sandbox into the cda docker network
docker rm -f $name 2>/dev/null
# docker run --privileged --name sandbox-hdp-security -h sandbox-hdp-security --network=cda --network-alias=sandbox-hdp-security -d hortonworks/sandbox-hdp-security:3.0
docker run --privileged --cpus="6.0" --memory="8g" --memory-swap="10g" --name $name -h $hostname --network=cda --network-alias=$hostname -d $image

#
#
docker rm -f sandbox-tomcat 2>/dev/null
docker run --privileged --name sandbox-tomcat -h sandbox-tomcat.hortonworks.com --network=cda --network-alias=sandbox-tomcat.hortonworks.com -d 'tomcat:9.0'

# Deploy the proxy container.  This script was generated by running
chmod +x ./proxy/generate-proxy-deploy-script.sh
./proxy/generate-proxy-deploy-script.sh

#
chmod +x ./proxy/proxy-deploy.sh
./proxy/proxy-deploy.sh
