#
server:
  port: 8100

#  
spring:
  application:
    name: sb-gateway-module
    instance-id: global
  output.ansi.enabled: ALWAYS

#
  security:
    oauth2:
      resourceserver:
        id: sb-gateway-module
        jwk:
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        jwt:
          issuer-uri: https://sts.windows.net/da5ac8f7-13d6-46e7-815d-012b01123148/
          audiences: api://7f1cf4d7-ca24-47c2-bf17-61a8a796679e

#
  cloud:
    gateway:
      routes:
        - id: sb-backend-module-r1
          uri: lb://SB-BACKEND-MODULE-DC-R1
          predicates:
            - Path=/api/v1/**
            - Header=X-Tenant-Id, DC-R1
          filters:
            - RewritePath=/api/v1/?(?<segment>.*), /api/v1/r1/$\{segment}
            - AddRequestParameter=src, gw
#            - PrefixPath=/r1

        - id: sb-backend-module-r2
          uri: lb://SB-BACKEND-MODULE-DC-R2
          predicates:
            - Path=/api/v1/**
            - Header=X-Tenant-Id, DC-R2
          filters:
            - RewritePath=/api/v1/?(?<segment>.*), /api/v1/r2/$\{segment}
            - AddRequestParameter=src, gw
#            - PrefixPath=/r1
#            - AddRequestHeader=X-Tenant-Id, DC-R2

        - id: bd-frontend-module
          uri: lb://SB-FRONTEND-MODULE
          predicates:
            - Path=/web/**
          filters:
            - RewritePath=/web/?(?<segment>.*), /web/v1/r2/$\{segment}

        - id: no-service
          uri: lb://NO-SERVICE
          predicates:
            - Path=/api/v1/no-service/**
            

# Eureka discovery client config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.application.instance-id}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

#
management:
  endpoints:
    web:
      exposure:
        include: "*"

#
logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
