# docker-compose build
# docker-compose up -d
# docker-compose scale nodemanager=X; # X=integer number --> allows to add more nodes to the hadoop cluster for testing

version: '3'
services:
  #
  # postgres setup
  #
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    entrypoint: /init-setup.sh
    env_file:
      - docker/.env
    volumes:
      - /apps/hostpath:/apps/hostpath
      - /custom/mount:/var/lib/postgresql/data
      - ./docker/postgres/init-setup.sh:/init-setup.sh
  #
  #
  #
  namenode:
    image: hadoop:3.2.1
    ports:
      - "5432:5432"
    entrypoint: /init-setup.sh
    env_file:
      - docker/.env
    volumes:
      - /apps/hostpath:/apps/hostpath
      - /custom/mount:/var/lib/postgresql/data
      - ./docker/postgres/init-setup.sh:/init-setup.sh