# docker-compose build
# docker-compose up -d
# docker-compose scale nodemanager=X; # X=integer number --> allows to add more nodes to the hadoop cluster for testing

version: '3.1'
services:
  #
  # postgres setup
  #
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
#    entrypoint: /init-setup.sh
    command: /init-setup.sh
    env_file:
      - docker/.env
    volumes:
      - /apps/hostpath:/apps/hostpath
      - ./docker/postgres/init-setup.sh:/init-setup.sh
  #
  #
  #
  namenode:
    image: dhc/hadoop:3.2.1
    build:
      context: .
      dockerfile: docker/hadoop/Dockerfile
    hostname: namenode
    ports:
      - "9000:9000"
      - "9866:9866"
      - "9870:9870"
      - "9864:9864"
#    entrypoint: /start-hdfs.sh
    command: /start-hdfs.sh
    env_file:
      - docker/.env
    environment:
      HDFS_MODE: SingleNode
    volumes:
      - /apps/hadoop-3.2.1:/opt/hadoop
      - /apps/hostpath:/apps/hostpath
      - ./docker/hadoop/start-hdfs.sh:/start-hdfs.sh
      - ./docker/hadoop/start-namenode.sh:/start-namenode.sh
  #
  #
  #