#
---
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-pvolume
  namespace: localstack
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/apps/hostpath"