#
---
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pvolume
  namespace: hadoop
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/apps/hostpath"