#
#
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvclaim
  namespace: hadoop
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi