# Default values for helm.
# This is a YAML-formatted file.

# This is to override the chart name.
nameOverride: "springboot-app"
fullnameOverride: "springboot-app"

# Declare variables to be passed into your templates.
author: Brijesh K Dhaker
environment: "docker"

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: brijeshdhaker/bd-spring-module
  pullPolicy: IfNotPresent
  tag: 1.0.0

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: docker-reg-cred



# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "sa-devops"

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels:
  env: dev
  type: spring-boot

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 9080

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
networkpolicies:
  enabled: false
  ingress: {}
  egress: {}

ingress:
  enabled: false
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: springboot-app.sandbox.net
      paths:
        - path: /api/v1
          pathType: ImplementationSpecific
  tls:
    - secretName: springboot-app-tls
      hosts:
        - springboot-app.sandbox.net

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /api/v1
    port: http
readinessProbe:
  httpGet:
    path: /api/v1
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: vol-sandbox
    hostPath:
      path: /apps/sandbox
      type: Directory
  - name: vol-secret
    secret:
     secretName: password-secret
     optional: false
  - name: vol-configmap
    configMap:
      name: bd-spring-module-configmap
      optional: false
      items:
      - key: application-docker.yaml
        path: application-docker.yaml
      - key: application.yaml
        path: application.yaml
# Additional volumeMounts on the output Deployment definition.
volumeMounts:
 - name: vol-sandbox
   mountPath: "/apps/sandbox"
   readOnly: true
 - name: vol-secret
   mountPath: "/apps/secrets"
   readOnly: true
 - name: vol-configmap
   mountPath: "/apps/configs"
   readOnly: true
nodeSelector: {}

tolerations: []

affinity: {}

favorite:
  food: Bread
  drink: coffee
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
  - pineapple