#
# docker-compose -H tcp://raspberry:2375 -f dc-jupyternb.yml up -d
#
version: '3.9'
#
services:
#
  jupyternb:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyternb
    hostname: jupyternb
    ports:
      - "8888:8888"
      - "7777:7777"
      - "2222:2222"
    volumes:
      - sandbox_apps_path:/apps
      - /apps/sandbox/jupyternb/notebook:/home/jovyan/work
    environment:
      KUBECONFIG: /home/notebook/.kube/config
#

#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_security_secrets:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net