#
# docker-compose -H tcp://raspberry:2375 -f dc-notebook.yml up -d
#
version: '3.9'
#
services:
# /usr/local/spark
  notebook:
    image: brijeshdhaker/notebook:3.5.0
    container_name: notebook
    hostname: notebook.sandbox.net
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - sandbox_apps_path:/apps
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - ./conf/spark/conf:/usr/local/spark/conf
      - /apps/sandbox/notebooks:/home/jovyan/notebooks
    environment:
      KUBECONFIG: /home/notebook/.kube/config
#

#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_security_secrets:
    external: true
  #
  sandbox_hadoop_334:
    external: true
  sandbox_hive_313:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net