#
# docker-compose -H tcp://raspberry:2375 -f dc-notebook.yml up -d
# /home/jovyan/work
# brijeshdhaker/notebook:3.5.0
version: '3.9'
#
services:
# /usr/local/spark
  notebook:
    image: brijeshdhaker/notebook:3.5.0
    container_name: notebook
    hostname: notebook.sandbox.net
    user: root
#    command:
#      - "jupyter lab --port=8888 --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --notebook-dir=/home/notebooks/"
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - sandbox_apps_path:/apps
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
      - ./conf/spark/conf:/usr/local/spark/conf
      - sandbox_hadoop_334:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop
      - /opt/maven-3.6.3:/opt/maven-3.6.3
      - ./conf/maven/settings.xml:/home/jovyan/.m2/settings.xml
      - sandbox_hive_313:/opt/hive
      - ./conf/hive/client/hive-site.xml:/opt/hive/conf/hive-site.xml
      - /apps/sandbox/notebooks:/home/jovyan/work/notebooks
    environment:
      GRANT_SUDO: yes
      KUBECONFIG: /home/notebook/.kube/config
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      SPARK_HOME: /usr/local/spark
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      HIVE_HOME: /opt/hive
      HIVE_CONF_DIR: /opt/hive/conf
      PYARROW_IGNORE_TIMEZONE: 1
#    env_file:
#      - ./envs/docker_clients.env
#

#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_security_secrets:
    external: true
  #
  sandbox_hadoop_334:
    external: true
  sandbox_hive_313:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net