#
# docker volume create --name sandbox_security_secrets --opt type=none --opt device=/apps/security/ssl --opt o=bind
# docker volume create --name sandbox_zookeeper311_data --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop311/data --opt o=bind
# docker volume create --name sandbox_zookeeper311_log --opt type=none --opt device=/apps/sandbox/zookeeper/hadoop311/log --opt o=bind
# docker volume create --name sandbox_kafka311_data --opt type=none --opt device=/apps/sandbox/kafka/hadoop311/data --opt o=bind
# docker volume create --name sandbox_kafka311_log --opt type=none --opt device=/apps/sandbox/kafka/hadoop311/log --opt o=bind
#
---
version: "3.9"

include:
  - dc-kdcserver.yml

services:
  #
  # Zookeeper Server
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    healthcheck:
      test: curl -f http://zookeeper.sandbox.net:8080/commands || exit 1
      retries: 20
      interval: 10s
    ports:
      - "2181:2181"
      - "2182:2182"
      - "28080:8080"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/zookeeper/secrets
      - sandbox_zookeeper311_data:/var/lib/zookeeper/data
      - sandbox_zookeeper311_log:/var/lib/zookeeper/log
      - ./conf/kerberos/krb5.conf:/etc/krb5.conf
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SECURE_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      KRB5_CONFIG: "/etc/krb5.conf"
      # ALLOW_UNSIGNED: "true"
      #
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /apps/security/ssl/zookeeper.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /apps/security/ssl/zookeeper.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      ZOOKEEPER_SSL_CLIENT_AUTH: "need"
      #
      ZOOKEEPER_AUTH_PROVIDER_X509: org.apache.zookeeper.server.auth.X509AuthenticationProvider
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      #
      KAFKA_OPTS: -Djava.security.auth.login.config=/apps/security/jaas/zookeeper-jaas.conf
        -Djava.security.krb5.conf=/etc/krb5.conf
        -Dsun.security.krb5.debug=false
        -Dkerberos.removeHostFromPrincipal=true
        -Dkerberos.removeRealmFromPrincipal=true
        -Dzookeeper.skipACL=true
        #-Dzookeeper.requireClientAuthScheme=sasl
        #-Dzookeeper.allowSaslFailedClients=false
      #-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    labels:
      - io.confluent.docker.testing=true
    extra_hosts:
      - "thinkpad.sandbox.net:172.18.0.1"

#
volumes:
  #
  sandbox_zookeeper311_data:
    external: true
  sandbox_zookeeper311_log:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net