#
#
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-pvclaim
  namespace: localstack
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi