#
server:
  port: 8080
  http2:
    enabled: true
#
spring:
  #
  application:
    name: bd-frontend-module
  output.ansi.enabled: ALWAYS
  #
  security:
    oauth2:
      resourceserver:
        id: api://7f1cf4d7-ca24-47c2-bf17-61a8a796679e
        jwk:
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        jwt:
          issuer-uri: https://login.microsoftonline.com/da5ac8f7-13d6-46e7-815d-012b01123148/oauth2/v2.0/token
          authorization:
            group-to-authorities:
              "bcd99935-c922-4289-8bee-174369c157a5": SANDBOX_DEFAULT
              "3c19f1ea-f9e3-47d0-9d4a-aa97c29d0867": SANDBOX_ADMIN
              "ebddcd37-20a5-4272-ae8d-7e90be4a7e46": SANDBOX_OPERATE
              "6489408e-121a-4d49-bb45-dbe074435179": SANDBOX_RW
              "29132c43-c263-4015-9f42-9c848d9b2f3b": SANDBOX_RO
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/da5ac8f7-13d6-46e7-815d-012b01123148/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: 7f1cf4d7-ca24-47c2-bf17-61a8a796679e
            client-secret: sVy8Q~jmLAlU3N9viydtvGBBGb5WL2XpBtCq_aqU
            scope:
              - openid
              - email
              - profile
#
logging:
  level:
    root: info